<!doctype html>
<html>
  <head>
    <title>LGSF Dashboard</title>
    <link rel="stylesheet"  href="/lgsf-dashboard/assets/css/styles.css">
    <link rel="shortcut icon" href="https://democracyclub.org.uk/static/images/logo_icon.png">
  </head>
  <body>
    <div class="ds-page">
      <a class="ds-skip-link" href="#main">skip to content</a>

      <header class="ds-header">
        <a class="ds-skip-link" href="#main">skip to content</a>
        <a class="ds-logo" href="/lgsf-dashboard/">
          <img src="https://DemocracyClub.github.io/design-system/images/logo_icon.svg" alt="" />
          <span>LGSF Logbooks</span>
        </a>

      </header>


      <main id="main" tabindex="-1" class="ds-stack">

        
<style>

    pre {
        height:400px;
        overflow-x: scroll;
        width:100%
    }
</style>




  


  <h2 id="2022-05-04-13-46">2022-05-04</h2>
  <div class="ds-card">
  <div class="ds-card-body">
    <dl class="ds-descriptions">
      <div>
        <dt>Duration</dt>
        <dd>9 seconds</dd>
      </div>
      <div>
        <dt>Start</dt>
        <dd>2022-05-04 13:46:14.374831</dd>
      </div>
      <div>
        <dt>End</dt>
        <dd>2022-05-04 13:46:23.564530</dd>
      </div>
      <div>
        <dt>Status code</dt>
        <dd>0</dd>
      </div>
      <div>
        <dt>Error</dt>
        <dd></dd>
      </div>
    </dl>
  </div>
  </div>

  <h3>Run log</h3>
  <pre>[13:46:14] Fetching Scraper for: OXO                              handlers.py:23
           Begin attempting to scrape: OXO                        handlers.py:27
           Deleting existing data...                                 base.py:230
[13:46:15] Getting all files in OXO...                               base.py:182
           Getting all files in OXO/json...                          base.py:182
           ...found 48 files in OXO/json                             base.py:198
           Getting all files in OXO/raw...                           base.py:182
           ...found 48 files in OXO/raw                              base.py:198
           ...found 97 files in OXO                                  base.py:198
           Deleting batch no. 1 consisting of 97 files               base.py:207
[13:46:16] ...data deleted.                                          base.py:237
           Scraping from https://mycouncil.oxford.gov.uk/mgWebService base.py:42
           .asmx/GetCouncillorsByWard                                           
[13:46:20] Committing batch 1 consisting of 92 files                 base.py:265
[13:46:21] Committing batch 2 consisting of 4 files                  base.py:265
[13:46:23] Finished attempting to scrape: OXO                        base.py:315
</pre>
  

  


  <h2 id="2022-05-03-13-40">2022-05-03</h2>
  <div class="ds-card">
  <div class="ds-card-body">
    <dl class="ds-descriptions">
      <div>
        <dt>Duration</dt>
        <dd>9 seconds</dd>
      </div>
      <div>
        <dt>Start</dt>
        <dd>2022-05-03 13:40:47.074148</dd>
      </div>
      <div>
        <dt>End</dt>
        <dd>2022-05-03 13:40:56.862635</dd>
      </div>
      <div>
        <dt>Status code</dt>
        <dd>0</dd>
      </div>
      <div>
        <dt>Error</dt>
        <dd></dd>
      </div>
    </dl>
  </div>
  </div>

  <h3>Run log</h3>
  <pre>[13:40:47] Fetching Scraper for: OXO                              handlers.py:23
           Begin attempting to scrape: OXO                        handlers.py:27
           Deleting existing data...                                 base.py:230
           Getting all files in OXO...                               base.py:182
[13:40:48] Getting all files in OXO/json...                          base.py:182
           ...found 48 files in OXO/json                             base.py:198
           Getting all files in OXO/raw...                           base.py:182
           ...found 48 files in OXO/raw                              base.py:198
           ...found 97 files in OXO                                  base.py:198
           Deleting batch no. 1 consisting of 97 files               base.py:207
[13:40:49] ...data deleted.                                          base.py:237
           Scraping from https://mycouncil.oxford.gov.uk/mgWebService base.py:42
           .asmx/GetCouncillorsByWard                                           
[13:40:54] Committing batch 1 consisting of 92 files                 base.py:265
[13:40:55] Committing batch 2 consisting of 4 files                  base.py:265
[13:40:56] Finished attempting to scrape: OXO                        base.py:315
</pre>
  

  


  <h2 id="2022-05-02-14-08">2022-05-02</h2>
  <div class="ds-card">
  <div class="ds-card-body">
    <dl class="ds-descriptions">
      <div>
        <dt>Duration</dt>
        <dd>9 seconds</dd>
      </div>
      <div>
        <dt>Start</dt>
        <dd>2022-05-02 14:08:06.992373</dd>
      </div>
      <div>
        <dt>End</dt>
        <dd>2022-05-02 14:08:16.886785</dd>
      </div>
      <div>
        <dt>Status code</dt>
        <dd>0</dd>
      </div>
      <div>
        <dt>Error</dt>
        <dd></dd>
      </div>
    </dl>
  </div>
  </div>

  <h3>Run log</h3>
  <pre>[14:08:06] Fetching Scraper for: OXO                              handlers.py:23
[14:08:07] Begin attempting to scrape: OXO                        handlers.py:27
           Deleting existing data...                                 base.py:230
           Getting all files in OXO...                               base.py:182
[14:08:08] Getting all files in OXO/json...                          base.py:182
           ...found 48 files in OXO/json                             base.py:198
           Getting all files in OXO/raw...                           base.py:182
           ...found 48 files in OXO/raw                              base.py:198
           ...found 97 files in OXO                                  base.py:198
           Deleting batch no. 1 consisting of 97 files               base.py:207
[14:08:09] ...data deleted.                                          base.py:237
           Scraping from https://mycouncil.oxford.gov.uk/mgWebService base.py:42
           .asmx/GetCouncillorsByWard                                           
[14:08:14] Committing batch 1 consisting of 92 files                 base.py:265
[14:08:15] Committing batch 2 consisting of 4 files                  base.py:265
[14:08:16] Finished attempting to scrape: OXO                        base.py:315
</pre>
  

  


  <h2 id="2022-05-01-12-12">2022-05-01</h2>
  <div class="ds-card">
  <div class="ds-card-body">
    <dl class="ds-descriptions">
      <div>
        <dt>Duration</dt>
        <dd>9 seconds</dd>
      </div>
      <div>
        <dt>Start</dt>
        <dd>2022-05-01 12:12:12.060730</dd>
      </div>
      <div>
        <dt>End</dt>
        <dd>2022-05-01 12:12:21.412409</dd>
      </div>
      <div>
        <dt>Status code</dt>
        <dd>0</dd>
      </div>
      <div>
        <dt>Error</dt>
        <dd></dd>
      </div>
    </dl>
  </div>
  </div>

  <h3>Run log</h3>
  <pre>[12:12:12] Fetching Scraper for: OXO                              handlers.py:23
           Begin attempting to scrape: OXO                        handlers.py:27
[12:12:13] Deleting existing data...                                 base.py:230
[12:12:14] Getting all files in OXO...                               base.py:182
           Getting all files in OXO/json...                          base.py:182
           ...found 48 files in OXO/json                             base.py:198
           Getting all files in OXO/raw...                           base.py:182
           ...found 48 files in OXO/raw                              base.py:198
           ...found 97 files in OXO                                  base.py:198
           Deleting batch no. 1 consisting of 97 files               base.py:207
[12:12:15] ...data deleted.                                          base.py:237
           Scraping from https://mycouncil.oxford.gov.uk/mgWebService base.py:42
           .asmx/GetCouncillorsByWard                                           
[12:12:18] Committing batch 1 consisting of 92 files                 base.py:265
[12:12:20] Committing batch 2 consisting of 4 files                  base.py:265
[12:12:21] Finished attempting to scrape: OXO                        base.py:315
</pre>
  

  


  <h2 id="2022-04-30-14-16">2022-04-30</h2>
  <div class="ds-card">
  <div class="ds-card-body">
    <dl class="ds-descriptions">
      <div>
        <dt>Duration</dt>
        <dd>8 seconds</dd>
      </div>
      <div>
        <dt>Start</dt>
        <dd>2022-04-30 14:16:04.782938</dd>
      </div>
      <div>
        <dt>End</dt>
        <dd>2022-04-30 14:16:12.859345</dd>
      </div>
      <div>
        <dt>Status code</dt>
        <dd>0</dd>
      </div>
      <div>
        <dt>Error</dt>
        <dd></dd>
      </div>
    </dl>
  </div>
  </div>

  <h3>Run log</h3>
  <pre>[14:16:04] Fetching Scraper for: OXO                              handlers.py:23
           Begin attempting to scrape: OXO                        handlers.py:27
           Deleting existing data...                                 base.py:230
[14:16:05] Getting all files in OXO...                               base.py:182
           Getting all files in OXO/json...                          base.py:182
[14:16:06] ...found 48 files in OXO/json                             base.py:198
           Getting all files in OXO/raw...                           base.py:182
           ...found 48 files in OXO/raw                              base.py:198
           ...found 97 files in OXO                                  base.py:198
           Deleting batch no. 1 consisting of 97 files               base.py:207
[14:16:07] ...data deleted.                                          base.py:237
           Scraping from https://mycouncil.oxford.gov.uk/mgWebService base.py:42
           .asmx/GetCouncillorsByWard                                           
[14:16:10] Committing batch 1 consisting of 92 files                 base.py:265
[14:16:11] Committing batch 2 consisting of 4 files                  base.py:265
[14:16:12] Finished attempting to scrape: OXO                        base.py:315
</pre>
  

  


  <h2 id="2022-04-29-14-06">2022-04-29</h2>
  <div class="ds-card">
  <div class="ds-card-body">
    <dl class="ds-descriptions">
      <div>
        <dt>Duration</dt>
        <dd>8 seconds</dd>
      </div>
      <div>
        <dt>Start</dt>
        <dd>2022-04-29 14:06:40.602860</dd>
      </div>
      <div>
        <dt>End</dt>
        <dd>2022-04-29 14:06:48.769185</dd>
      </div>
      <div>
        <dt>Status code</dt>
        <dd>0</dd>
      </div>
      <div>
        <dt>Error</dt>
        <dd></dd>
      </div>
    </dl>
  </div>
  </div>

  <h3>Run log</h3>
  <pre>[14:06:40] Fetching Scraper for: OXO                              handlers.py:23
           Begin attempting to scrape: OXO                        handlers.py:27
           Deleting existing data...                                 base.py:230
[14:06:41] Getting all files in OXO...                               base.py:182
           Getting all files in OXO/json...                          base.py:182
           ...found 48 files in OXO/json                             base.py:198
           Getting all files in OXO/raw...                           base.py:182
[14:06:42] ...found 48 files in OXO/raw                              base.py:198
           ...found 97 files in OXO                                  base.py:198
           Deleting batch no. 1 consisting of 97 files               base.py:207
[14:06:43] ...data deleted.                                          base.py:237
           Scraping from https://mycouncil.oxford.gov.uk/mgWebService base.py:42
           .asmx/GetCouncillorsByWard                                           
[14:06:46] Committing batch 1 consisting of 92 files                 base.py:265
[14:06:47] Committing batch 2 consisting of 4 files                  base.py:265
[14:06:48] Finished attempting to scrape: OXO                        base.py:315
</pre>
  

  


  <h2 id="2022-04-28-12-08">2022-04-28</h2>
  <div class="ds-card">
  <div class="ds-card-body">
    <dl class="ds-descriptions">
      <div>
        <dt>Duration</dt>
        <dd>9 seconds</dd>
      </div>
      <div>
        <dt>Start</dt>
        <dd>2022-04-28 12:08:07.964602</dd>
      </div>
      <div>
        <dt>End</dt>
        <dd>2022-04-28 12:08:17.373539</dd>
      </div>
      <div>
        <dt>Status code</dt>
        <dd>0</dd>
      </div>
      <div>
        <dt>Error</dt>
        <dd></dd>
      </div>
    </dl>
  </div>
  </div>

  <h3>Run log</h3>
  <pre>[12:08:07] Fetching Scraper for: OXO                              handlers.py:23
           Begin attempting to scrape: OXO                        handlers.py:27
[12:08:08] Deleting existing data...                                 base.py:230
           Getting all files in OXO...                               base.py:182
[12:08:09] Getting all files in OXO/json...                          base.py:182
           ...found 48 files in OXO/json                             base.py:198
           Getting all files in OXO/raw...                           base.py:182
           ...found 48 files in OXO/raw                              base.py:198
           ...found 97 files in OXO                                  base.py:198
           Deleting batch no. 1 consisting of 97 files               base.py:207
[12:08:10] ...data deleted.                                          base.py:237
           Scraping from https://mycouncil.oxford.gov.uk/mgWebService base.py:42
           .asmx/GetCouncillorsByWard                                           
[12:08:14] Committing batch 1 consisting of 92 files                 base.py:265
[12:08:15] Committing batch 2 consisting of 4 files                  base.py:265
[12:08:17] Finished attempting to scrape: OXO                        base.py:315
</pre>
  

  


  <h2 id="2022-04-27-13-31">2022-04-27</h2>
  <div class="ds-card">
  <div class="ds-card-body">
    <dl class="ds-descriptions">
      <div>
        <dt>Duration</dt>
        <dd>8 seconds</dd>
      </div>
      <div>
        <dt>Start</dt>
        <dd>2022-04-27 13:31:44.779861</dd>
      </div>
      <div>
        <dt>End</dt>
        <dd>2022-04-27 13:31:53.334866</dd>
      </div>
      <div>
        <dt>Status code</dt>
        <dd>0</dd>
      </div>
      <div>
        <dt>Error</dt>
        <dd></dd>
      </div>
    </dl>
  </div>
  </div>

  <h3>Run log</h3>
  <pre>[13:31:44] Fetching Scraper for: OXO                              handlers.py:23
           Begin attempting to scrape: OXO                        handlers.py:27
           Deleting existing data...                                 base.py:230
[13:31:45] Getting all files in OXO...                               base.py:182
           Getting all files in OXO/json...                          base.py:182
[13:31:46] ...found 48 files in OXO/json                             base.py:198
           Getting all files in OXO/raw...                           base.py:182
           ...found 48 files in OXO/raw                              base.py:198
           ...found 97 files in OXO                                  base.py:198
           Deleting batch no. 1 consisting of 97 files               base.py:207
[13:31:47] ...data deleted.                                          base.py:237
           Scraping from https://mycouncil.oxford.gov.uk/mgWebService base.py:42
           .asmx/GetCouncillorsByWard                                           
[13:31:50] Committing batch 1 consisting of 92 files                 base.py:265
[13:31:51] Committing batch 2 consisting of 4 files                  base.py:265
[13:31:53] Finished attempting to scrape: OXO                        base.py:315
</pre>
  

  


  <h2 id="2022-04-26-11-55">2022-04-26</h2>
  <div class="ds-card">
  <div class="ds-card-body">
    <dl class="ds-descriptions">
      <div>
        <dt>Duration</dt>
        <dd>8 seconds</dd>
      </div>
      <div>
        <dt>Start</dt>
        <dd>2022-04-26 11:55:32.309418</dd>
      </div>
      <div>
        <dt>End</dt>
        <dd>2022-04-26 11:55:40.385779</dd>
      </div>
      <div>
        <dt>Status code</dt>
        <dd>0</dd>
      </div>
      <div>
        <dt>Error</dt>
        <dd></dd>
      </div>
    </dl>
  </div>
  </div>

  <h3>Run log</h3>
  <pre>[11:55:32] Fetching Scraper for: OXO                              handlers.py:23
           Begin attempting to scrape: OXO                        handlers.py:27
           Deleting existing data...                                 base.py:230
[11:55:33] Getting all files in OXO...                               base.py:182
           Getting all files in OXO/json...                          base.py:182
           ...found 48 files in OXO/json                             base.py:198
           Getting all files in OXO/raw...                           base.py:182
           ...found 48 files in OXO/raw                              base.py:198
           ...found 97 files in OXO                                  base.py:198
           Deleting batch no. 1 consisting of 97 files               base.py:207
[11:55:34] ...data deleted.                                          base.py:237
           Scraping from https://mycouncil.oxford.gov.uk/mgWebService base.py:42
           .asmx/GetCouncillorsByWard                                           
[11:55:37] Committing batch 1 consisting of 92 files                 base.py:265
[11:55:39] Committing batch 2 consisting of 4 files                  base.py:265
[11:55:40] Finished attempting to scrape: OXO                        base.py:315
</pre>
  

  


  <h2 id="2022-04-25-13-09">2022-04-25</h2>
  <div class="ds-card">
  <div class="ds-card-body">
    <dl class="ds-descriptions">
      <div>
        <dt>Duration</dt>
        <dd>8 seconds</dd>
      </div>
      <div>
        <dt>Start</dt>
        <dd>2022-04-25 13:09:06.759352</dd>
      </div>
      <div>
        <dt>End</dt>
        <dd>2022-04-25 13:09:14.967952</dd>
      </div>
      <div>
        <dt>Status code</dt>
        <dd>0</dd>
      </div>
      <div>
        <dt>Error</dt>
        <dd></dd>
      </div>
    </dl>
  </div>
  </div>

  <h3>Run log</h3>
  <pre>[13:09:06] Fetching Scraper for: OXO                              handlers.py:23
           Begin attempting to scrape: OXO                        handlers.py:27
           Deleting existing data...                                 base.py:230
[13:09:07] Getting all files in OXO...                               base.py:182
           Getting all files in OXO/json...                          base.py:182
           ...found 48 files in OXO/json                             base.py:198
           Getting all files in OXO/raw...                           base.py:182
[13:09:08] ...found 48 files in OXO/raw                              base.py:198
           ...found 97 files in OXO                                  base.py:198
           Deleting batch no. 1 consisting of 97 files               base.py:207
[13:09:09] ...data deleted.                                          base.py:237
           Scraping from https://mycouncil.oxford.gov.uk/mgWebService base.py:42
           .asmx/GetCouncillorsByWard                                           
[13:09:12] Committing batch 1 consisting of 92 files                 base.py:265
[13:09:13] Committing batch 2 consisting of 4 files                  base.py:265
[13:09:14] Finished attempting to scrape: OXO                        base.py:315
</pre>
  

  


  <h2 id="2022-04-24-19-29">2022-04-24</h2>
  <div class="ds-card">
  <div class="ds-card-body">
    <dl class="ds-descriptions">
      <div>
        <dt>Duration</dt>
        <dd>7 seconds</dd>
      </div>
      <div>
        <dt>Start</dt>
        <dd>2022-04-24 19:29:11.808480</dd>
      </div>
      <div>
        <dt>End</dt>
        <dd>2022-04-24 19:29:19.664368</dd>
      </div>
      <div>
        <dt>Status code</dt>
        <dd>0</dd>
      </div>
      <div>
        <dt>Error</dt>
        <dd></dd>
      </div>
    </dl>
  </div>
  </div>

  <h3>Run log</h3>
  <pre>[19:29:11] Fetching Scraper for: OXO                              handlers.py:23
           Begin attempting to scrape: OXO                        handlers.py:27
[19:29:12] Deleting existing data...                                 base.py:230
           Getting all files in OXO...                               base.py:182
           ...found 1 files in OXO                                   base.py:198
           Deleting batch no. 1 consisting of 1 files                base.py:207
[19:29:13] ...data deleted.                                          base.py:237
           Scraping from https://mycouncil.oxford.gov.uk/mgWebService base.py:42
           .asmx/GetCouncillorsByWard                                           
[19:29:16] Committing batch 1 consisting of 92 files                 base.py:265
[19:29:18] Committing batch 2 consisting of 4 files                  base.py:265
[19:29:19] Finished attempting to scrape: OXO                        base.py:315
</pre>
  

  


  <h2 id="2022-04-23-13-09">2022-04-23</h2>
  <div class="ds-card">
  <div class="ds-card-body">
    <dl class="ds-descriptions">
      <div>
        <dt>Duration</dt>
        <dd>2 seconds</dd>
      </div>
      <div>
        <dt>Start</dt>
        <dd>2022-04-23 13:09:53.328015</dd>
      </div>
      <div>
        <dt>End</dt>
        <dd>2022-04-23 13:09:55.711903</dd>
      </div>
      <div>
        <dt>Status code</dt>
        <dd>1</dd>
      </div>
      <div>
        <dt>Error</dt>
        <dd>Traceback (most recent call last):
  File "/opt/python/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/opt/python/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/opt/python/urllib3/connectionpool.py", line 1040, in _validate_conn
    conn.connect()
  File "/opt/python/urllib3/connection.py", line 416, in connect
    self.sock = ssl_wrap_socket(
  File "/opt/python/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/opt/python/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/var/lang/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/var/lang/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/var/lang/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/python/requests/adapters.py", line 440, in send
    resp = conn.urlopen(
  File "/opt/python/urllib3/connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "/opt/python/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='mycouncil.oxford.gov.uk', port=443): Max retries exceeded with url: /mgWebService.asmx/GetCouncillorsByWard (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/task/lgsf/aws_lambda/handlers.py", line 32, in scraper_worker_handler
    scraper.run(run_log)
  File "/var/task/lgsf/councillors/scrapers.py", line 174, in run
    wards = self.get_councillors()
  File "/var/task/lgsf/councillors/scrapers.py", line 191, in get_councillors
    req = self.get(self.format_councillor_api_url(), verify=self.verify_requests)
  File "/var/task/lgsf/scrapers/base.py", line 46, in get
    response = requests.get(url, headers=headers, verify=verify)
  File "/opt/python/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/opt/python/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/opt/python/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/python/requests/sessions.py", line 667, in send
    history = [resp for resp in gen]
  File "/opt/python/requests/sessions.py", line 667, in <listcomp>
    history = [resp for resp in gen]
  File "/opt/python/requests/sessions.py", line 237, in resolve_redirects
    resp = self.send(
  File "/opt/python/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/opt/python/requests/adapters.py", line 517, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='mycouncil.oxford.gov.uk', port=443): Max retries exceeded with url: /mgWebService.asmx/GetCouncillorsByWard (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))
</dd>
      </div>
    </dl>
  </div>
  </div>

  <h3>Run log</h3>
  <pre>[13:09:53] Fetching Scraper for: OXO                              handlers.py:23
           Begin attempting to scrape: OXO                        handlers.py:27
           Deleting existing data...                                 base.py:228
[13:09:54] Getting all files in OXO...                               base.py:180
           ...found 1 files in OXO                                   base.py:196
           Deleting batch no. 1 consisting of 1 files                base.py:205
[13:09:55] ...data deleted.                                          base.py:235
           Scraping from http://mycouncil.oxford.gov.uk/mgWebService. base.py:40
           asmx/GetCouncillorsByWard                                            
           HTTPSConnectionPool(host='mycouncil.oxford.gov.uk',    handlers.py:36
           port=443): Max retries exceeded with url:                            
           /mgWebService.asmx/GetCouncillorsByWard (Caused by                   
           SSLError(SSLCertVerificationError(1, '[SSL:                          
           CERTIFICATE_VERIFY_FAILED] certificate verify failed:                
           unable to get local issuer certificate                               
           (_ssl.c:1131)')))                                                    
           Finished attempting to scrape: OXO                        base.py:313
</pre>
  

  


  <h2 id="2022-04-22-11-38">2022-04-22</h2>
  <div class="ds-card">
  <div class="ds-card-body">
    <dl class="ds-descriptions">
      <div>
        <dt>Duration</dt>
        <dd>2 seconds</dd>
      </div>
      <div>
        <dt>Start</dt>
        <dd>2022-04-22 11:38:20.086377</dd>
      </div>
      <div>
        <dt>End</dt>
        <dd>2022-04-22 11:38:22.679457</dd>
      </div>
      <div>
        <dt>Status code</dt>
        <dd>1</dd>
      </div>
      <div>
        <dt>Error</dt>
        <dd>Traceback (most recent call last):
  File "/opt/python/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/opt/python/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/opt/python/urllib3/connectionpool.py", line 1040, in _validate_conn
    conn.connect()
  File "/opt/python/urllib3/connection.py", line 416, in connect
    self.sock = ssl_wrap_socket(
  File "/opt/python/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/opt/python/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/var/lang/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/var/lang/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/var/lang/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/python/requests/adapters.py", line 440, in send
    resp = conn.urlopen(
  File "/opt/python/urllib3/connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "/opt/python/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='mycouncil.oxford.gov.uk', port=443): Max retries exceeded with url: /mgWebService.asmx/GetCouncillorsByWard (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/task/lgsf/aws_lambda/handlers.py", line 32, in scraper_worker_handler
    scraper.run(run_log)
  File "/var/task/lgsf/councillors/scrapers.py", line 174, in run
    wards = self.get_councillors()
  File "/var/task/lgsf/councillors/scrapers.py", line 191, in get_councillors
    req = self.get(self.format_councillor_api_url(), verify=self.verify_requests)
  File "/var/task/lgsf/scrapers/base.py", line 46, in get
    response = requests.get(url, headers=headers, verify=verify)
  File "/opt/python/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/opt/python/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/opt/python/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/python/requests/sessions.py", line 667, in send
    history = [resp for resp in gen]
  File "/opt/python/requests/sessions.py", line 667, in <listcomp>
    history = [resp for resp in gen]
  File "/opt/python/requests/sessions.py", line 237, in resolve_redirects
    resp = self.send(
  File "/opt/python/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/opt/python/requests/adapters.py", line 517, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='mycouncil.oxford.gov.uk', port=443): Max retries exceeded with url: /mgWebService.asmx/GetCouncillorsByWard (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))
</dd>
      </div>
    </dl>
  </div>
  </div>

  <h3>Run log</h3>
  <pre>[11:38:20] Fetching Scraper for: OXO                              handlers.py:23
           Begin attempting to scrape: OXO                        handlers.py:27
           Deleting existing data...                                 base.py:228
           Getting all files in OXO...                               base.py:180
[11:38:21] ...found 1 files in OXO                                   base.py:196
           Deleting batch no. 1 consisting of 1 files                base.py:205
[11:38:22] ...data deleted.                                          base.py:235
           Scraping from http://mycouncil.oxford.gov.uk/mgWebService. base.py:40
           asmx/GetCouncillorsByWard                                            
           HTTPSConnectionPool(host='mycouncil.oxford.gov.uk',    handlers.py:36
           port=443): Max retries exceeded with url:                            
           /mgWebService.asmx/GetCouncillorsByWard (Caused by                   
           SSLError(SSLCertVerificationError(1, '[SSL:                          
           CERTIFICATE_VERIFY_FAILED] certificate verify failed:                
           unable to get local issuer certificate                               
           (_ssl.c:1131)')))                                                    
           Finished attempting to scrape: OXO                        base.py:313
</pre>
  

  


  <h2 id="2022-04-21-12-07">2022-04-21</h2>
  <div class="ds-card">
  <div class="ds-card-body">
    <dl class="ds-descriptions">
      <div>
        <dt>Duration</dt>
        <dd>2 seconds</dd>
      </div>
      <div>
        <dt>Start</dt>
        <dd>2022-04-21 12:07:30.698067</dd>
      </div>
      <div>
        <dt>End</dt>
        <dd>2022-04-21 12:07:32.887529</dd>
      </div>
      <div>
        <dt>Status code</dt>
        <dd>1</dd>
      </div>
      <div>
        <dt>Error</dt>
        <dd>Traceback (most recent call last):
  File "/opt/python/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/opt/python/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/opt/python/urllib3/connectionpool.py", line 1040, in _validate_conn
    conn.connect()
  File "/opt/python/urllib3/connection.py", line 416, in connect
    self.sock = ssl_wrap_socket(
  File "/opt/python/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/opt/python/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/var/lang/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/var/lang/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/var/lang/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/python/requests/adapters.py", line 440, in send
    resp = conn.urlopen(
  File "/opt/python/urllib3/connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "/opt/python/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='mycouncil.oxford.gov.uk', port=443): Max retries exceeded with url: /mgWebService.asmx/GetCouncillorsByWard (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/task/lgsf/aws_lambda/handlers.py", line 32, in scraper_worker_handler
    scraper.run(run_log)
  File "/var/task/lgsf/councillors/scrapers.py", line 166, in run
    wards = self.get_councillors()
  File "/var/task/lgsf/councillors/scrapers.py", line 183, in get_councillors
    req = self.get(self.format_councillor_api_url(), verify=self.verify_requests)
  File "/var/task/lgsf/scrapers/base.py", line 46, in get
    response = requests.get(url, headers=headers, verify=verify)
  File "/opt/python/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/opt/python/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/opt/python/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/python/requests/sessions.py", line 667, in send
    history = [resp for resp in gen]
  File "/opt/python/requests/sessions.py", line 667, in <listcomp>
    history = [resp for resp in gen]
  File "/opt/python/requests/sessions.py", line 237, in resolve_redirects
    resp = self.send(
  File "/opt/python/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/opt/python/requests/adapters.py", line 517, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='mycouncil.oxford.gov.uk', port=443): Max retries exceeded with url: /mgWebService.asmx/GetCouncillorsByWard (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))
</dd>
      </div>
    </dl>
  </div>
  </div>

  <h3>Run log</h3>
  <pre>[12:07:30] Fetching Scraper for: OXO                              handlers.py:23
           Begin attempting to scrape: OXO                        handlers.py:27
           Deleting existing data...                                 base.py:228
[12:07:31] Getting all files in OXO...                               base.py:180
           ...found 1 files in OXO                                   base.py:196
           Deleting batch no. 1 consisting of 1 files                base.py:205
[12:07:32] ...data deleted.                                          base.py:235
           Scraping from http://mycouncil.oxford.gov.uk/mgWebService. base.py:40
           asmx/GetCouncillorsByWard                                            
           HTTPSConnectionPool(host='mycouncil.oxford.gov.uk',    handlers.py:36
           port=443): Max retries exceeded with url:                            
           /mgWebService.asmx/GetCouncillorsByWard (Caused by                   
           SSLError(SSLCertVerificationError(1, '[SSL:                          
           CERTIFICATE_VERIFY_FAILED] certificate verify failed:                
           unable to get local issuer certificate                               
           (_ssl.c:1131)')))                                                    
           Finished attempting to scrape: OXO                        base.py:313
</pre>
  

  


  <h2 id="2022-04-20-12-06">2022-04-20</h2>
  <div class="ds-card">
  <div class="ds-card-body">
    <dl class="ds-descriptions">
      <div>
        <dt>Duration</dt>
        <dd>2 seconds</dd>
      </div>
      <div>
        <dt>Start</dt>
        <dd>2022-04-20 12:06:48.744861</dd>
      </div>
      <div>
        <dt>End</dt>
        <dd>2022-04-20 12:06:51.144497</dd>
      </div>
      <div>
        <dt>Status code</dt>
        <dd>1</dd>
      </div>
      <div>
        <dt>Error</dt>
        <dd>Traceback (most recent call last):
  File "/opt/python/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/opt/python/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/opt/python/urllib3/connectionpool.py", line 1040, in _validate_conn
    conn.connect()
  File "/opt/python/urllib3/connection.py", line 416, in connect
    self.sock = ssl_wrap_socket(
  File "/opt/python/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/opt/python/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/var/lang/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/var/lang/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/var/lang/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/python/requests/adapters.py", line 440, in send
    resp = conn.urlopen(
  File "/opt/python/urllib3/connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "/opt/python/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='mycouncil.oxford.gov.uk', port=443): Max retries exceeded with url: /mgWebService.asmx/GetCouncillorsByWard (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/task/lgsf/aws_lambda/handlers.py", line 32, in scraper_worker_handler
    scraper.run(run_log)
  File "/var/task/lgsf/councillors/scrapers.py", line 166, in run
    wards = self.get_councillors()
  File "/var/task/lgsf/councillors/scrapers.py", line 183, in get_councillors
    req = self.get(self.format_councillor_api_url(), verify=self.verify_requests)
  File "/var/task/lgsf/scrapers/base.py", line 46, in get
    response = requests.get(url, headers=headers, verify=verify)
  File "/opt/python/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/opt/python/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/opt/python/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/python/requests/sessions.py", line 667, in send
    history = [resp for resp in gen]
  File "/opt/python/requests/sessions.py", line 667, in <listcomp>
    history = [resp for resp in gen]
  File "/opt/python/requests/sessions.py", line 237, in resolve_redirects
    resp = self.send(
  File "/opt/python/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/opt/python/requests/adapters.py", line 517, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='mycouncil.oxford.gov.uk', port=443): Max retries exceeded with url: /mgWebService.asmx/GetCouncillorsByWard (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))
</dd>
      </div>
    </dl>
  </div>
  </div>

  <h3>Run log</h3>
  <pre>[12:06:48] Fetching Scraper for: OXO                              handlers.py:23
           Begin attempting to scrape: OXO                        handlers.py:27
           Deleting existing data...                                 base.py:228
[12:06:49] Getting all files in OXO...                               base.py:180
           ...found 1 files in OXO                                   base.py:196
           Deleting batch no. 1 consisting of 1 files                base.py:205
[12:06:50] ...data deleted.                                          base.py:235
           Scraping from http://mycouncil.oxford.gov.uk/mgWebService. base.py:40
           asmx/GetCouncillorsByWard                                            
           HTTPSConnectionPool(host='mycouncil.oxford.gov.uk',    handlers.py:36
           port=443): Max retries exceeded with url:                            
           /mgWebService.asmx/GetCouncillorsByWard (Caused by                   
           SSLError(SSLCertVerificationError(1, '[SSL:                          
           CERTIFICATE_VERIFY_FAILED] certificate verify failed:                
           unable to get local issuer certificate                               
           (_ssl.c:1131)')))                                                    
[12:06:51] Finished attempting to scrape: OXO                        base.py:313
</pre>
  

  


  <h2 id="2022-04-19-17-37">2022-04-19</h2>
  <div class="ds-card">
  <div class="ds-card-body">
    <dl class="ds-descriptions">
      <div>
        <dt>Duration</dt>
        <dd>2 seconds</dd>
      </div>
      <div>
        <dt>Start</dt>
        <dd>2022-04-19 17:37:12.439734</dd>
      </div>
      <div>
        <dt>End</dt>
        <dd>2022-04-19 17:37:14.767169</dd>
      </div>
      <div>
        <dt>Status code</dt>
        <dd>1</dd>
      </div>
      <div>
        <dt>Error</dt>
        <dd>Traceback (most recent call last):
  File "/opt/python/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/opt/python/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/opt/python/urllib3/connectionpool.py", line 1040, in _validate_conn
    conn.connect()
  File "/opt/python/urllib3/connection.py", line 416, in connect
    self.sock = ssl_wrap_socket(
  File "/opt/python/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/opt/python/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/var/lang/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/var/lang/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/var/lang/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/python/requests/adapters.py", line 440, in send
    resp = conn.urlopen(
  File "/opt/python/urllib3/connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "/opt/python/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='mycouncil.oxford.gov.uk', port=443): Max retries exceeded with url: /mgWebService.asmx/GetCouncillorsByWard (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/task/lgsf/aws_lambda/handlers.py", line 32, in scraper_worker_handler
    scraper.run(run_log)
  File "/var/task/lgsf/councillors/scrapers.py", line 166, in run
    wards = self.get_councillors()
  File "/var/task/lgsf/councillors/scrapers.py", line 183, in get_councillors
    req = self.get(self.format_councillor_api_url(), verify=self.verify_requests)
  File "/var/task/lgsf/scrapers/base.py", line 46, in get
    response = requests.get(url, headers=headers, verify=verify)
  File "/opt/python/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/opt/python/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/opt/python/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/python/requests/sessions.py", line 667, in send
    history = [resp for resp in gen]
  File "/opt/python/requests/sessions.py", line 667, in <listcomp>
    history = [resp for resp in gen]
  File "/opt/python/requests/sessions.py", line 237, in resolve_redirects
    resp = self.send(
  File "/opt/python/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/opt/python/requests/adapters.py", line 517, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='mycouncil.oxford.gov.uk', port=443): Max retries exceeded with url: /mgWebService.asmx/GetCouncillorsByWard (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))
</dd>
      </div>
    </dl>
  </div>
  </div>

  <h3>Run log</h3>
  <pre>[17:37:12] Fetching Scraper for: OXO                              handlers.py:23
           Begin attempting to scrape: OXO                        handlers.py:27
           Deleting existing data...                                 base.py:228
[17:37:13] Getting all files in OXO...                               base.py:180
           ...found 1 files in OXO                                   base.py:196
           Deleting batch no. 1 consisting of 1 files                base.py:205
[17:37:14] ...data deleted.                                          base.py:235
           Scraping from http://mycouncil.oxford.gov.uk/mgWebService. base.py:40
           asmx/GetCouncillorsByWard                                            
           HTTPSConnectionPool(host='mycouncil.oxford.gov.uk',    handlers.py:36
           port=443): Max retries exceeded with url:                            
           /mgWebService.asmx/GetCouncillorsByWard (Caused by                   
           SSLError(SSLCertVerificationError(1, '[SSL:                          
           CERTIFICATE_VERIFY_FAILED] certificate verify failed:                
           unable to get local issuer certificate                               
           (_ssl.c:1131)')))                                                    
           Finished attempting to scrape: OXO                        base.py:313
</pre>
  

  


  <h2 id="2022-04-18-11-28">2022-04-18</h2>
  <div class="ds-card">
  <div class="ds-card-body">
    <dl class="ds-descriptions">
      <div>
        <dt>Duration</dt>
        <dd>2 seconds</dd>
      </div>
      <div>
        <dt>Start</dt>
        <dd>2022-04-18 11:28:10.512724</dd>
      </div>
      <div>
        <dt>End</dt>
        <dd>2022-04-18 11:28:12.891872</dd>
      </div>
      <div>
        <dt>Status code</dt>
        <dd>1</dd>
      </div>
      <div>
        <dt>Error</dt>
        <dd>Traceback (most recent call last):
  File "/opt/python/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/opt/python/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/opt/python/urllib3/connectionpool.py", line 1040, in _validate_conn
    conn.connect()
  File "/opt/python/urllib3/connection.py", line 416, in connect
    self.sock = ssl_wrap_socket(
  File "/opt/python/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/opt/python/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/var/lang/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/var/lang/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/var/lang/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/python/requests/adapters.py", line 440, in send
    resp = conn.urlopen(
  File "/opt/python/urllib3/connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "/opt/python/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='mycouncil.oxford.gov.uk', port=443): Max retries exceeded with url: /mgWebService.asmx/GetCouncillorsByWard (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/task/lgsf/aws_lambda/handlers.py", line 32, in scraper_worker_handler
    scraper.run(run_log)
  File "/var/task/lgsf/councillors/scrapers.py", line 166, in run
    wards = self.get_councillors()
  File "/var/task/lgsf/councillors/scrapers.py", line 183, in get_councillors
    req = self.get(self.format_councillor_api_url(), verify=self.verify_requests)
  File "/var/task/lgsf/scrapers/base.py", line 46, in get
    response = requests.get(url, headers=headers, verify=verify)
  File "/opt/python/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/opt/python/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/opt/python/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/python/requests/sessions.py", line 667, in send
    history = [resp for resp in gen]
  File "/opt/python/requests/sessions.py", line 667, in <listcomp>
    history = [resp for resp in gen]
  File "/opt/python/requests/sessions.py", line 237, in resolve_redirects
    resp = self.send(
  File "/opt/python/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/opt/python/requests/adapters.py", line 517, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='mycouncil.oxford.gov.uk', port=443): Max retries exceeded with url: /mgWebService.asmx/GetCouncillorsByWard (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))
</dd>
      </div>
    </dl>
  </div>
  </div>

  <h3>Run log</h3>
  <pre>[11:28:10] Fetching Scraper for: OXO                              handlers.py:23
           Begin attempting to scrape: OXO                        handlers.py:27
           Deleting existing data...                                 base.py:228
[11:28:11] Getting all files in OXO...                               base.py:180
           ...found 1 files in OXO                                   base.py:196
           Deleting batch no. 1 consisting of 1 files                base.py:205
[11:28:12] ...data deleted.                                          base.py:235
           Scraping from http://mycouncil.oxford.gov.uk/mgWebService. base.py:40
           asmx/GetCouncillorsByWard                                            
           HTTPSConnectionPool(host='mycouncil.oxford.gov.uk',    handlers.py:36
           port=443): Max retries exceeded with url:                            
           /mgWebService.asmx/GetCouncillorsByWard (Caused by                   
           SSLError(SSLCertVerificationError(1, '[SSL:                          
           CERTIFICATE_VERIFY_FAILED] certificate verify failed:                
           unable to get local issuer certificate                               
           (_ssl.c:1131)')))                                                    
           Finished attempting to scrape: OXO                        base.py:313
</pre>
  

  


  <h2 id="2022-04-17-16-26">2022-04-17</h2>
  <div class="ds-card">
  <div class="ds-card-body">
    <dl class="ds-descriptions">
      <div>
        <dt>Duration</dt>
        <dd>2 seconds</dd>
      </div>
      <div>
        <dt>Start</dt>
        <dd>2022-04-17 16:26:45.720263</dd>
      </div>
      <div>
        <dt>End</dt>
        <dd>2022-04-17 16:26:47.979667</dd>
      </div>
      <div>
        <dt>Status code</dt>
        <dd>1</dd>
      </div>
      <div>
        <dt>Error</dt>
        <dd>Traceback (most recent call last):
  File "/opt/python/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/opt/python/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/opt/python/urllib3/connectionpool.py", line 1040, in _validate_conn
    conn.connect()
  File "/opt/python/urllib3/connection.py", line 416, in connect
    self.sock = ssl_wrap_socket(
  File "/opt/python/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/opt/python/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/var/lang/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/var/lang/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/var/lang/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/python/requests/adapters.py", line 440, in send
    resp = conn.urlopen(
  File "/opt/python/urllib3/connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "/opt/python/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='mycouncil.oxford.gov.uk', port=443): Max retries exceeded with url: /mgWebService.asmx/GetCouncillorsByWard (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/task/lgsf/aws_lambda/handlers.py", line 32, in scraper_worker_handler
    scraper.run(run_log)
  File "/var/task/lgsf/councillors/scrapers.py", line 166, in run
    wards = self.get_councillors()
  File "/var/task/lgsf/councillors/scrapers.py", line 183, in get_councillors
    req = self.get(self.format_councillor_api_url(), verify=self.verify_requests)
  File "/var/task/lgsf/scrapers/base.py", line 46, in get
    response = requests.get(url, headers=headers, verify=verify)
  File "/opt/python/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/opt/python/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/opt/python/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/python/requests/sessions.py", line 667, in send
    history = [resp for resp in gen]
  File "/opt/python/requests/sessions.py", line 667, in <listcomp>
    history = [resp for resp in gen]
  File "/opt/python/requests/sessions.py", line 237, in resolve_redirects
    resp = self.send(
  File "/opt/python/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/opt/python/requests/adapters.py", line 517, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='mycouncil.oxford.gov.uk', port=443): Max retries exceeded with url: /mgWebService.asmx/GetCouncillorsByWard (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))
</dd>
      </div>
    </dl>
  </div>
  </div>

  <h3>Run log</h3>
  <pre>[16:26:45] Fetching Scraper for: OXO                              handlers.py:23
           Begin attempting to scrape: OXO                        handlers.py:27
           Deleting existing data...                                 base.py:228
[16:26:46] Getting all files in OXO...                               base.py:180
           ...found 1 files in OXO                                   base.py:196
           Deleting batch no. 1 consisting of 1 files                base.py:205
[16:26:47] ...data deleted.                                          base.py:235
           Scraping from http://mycouncil.oxford.gov.uk/mgWebService. base.py:40
           asmx/GetCouncillorsByWard                                            
           HTTPSConnectionPool(host='mycouncil.oxford.gov.uk',    handlers.py:36
           port=443): Max retries exceeded with url:                            
           /mgWebService.asmx/GetCouncillorsByWard (Caused by                   
           SSLError(SSLCertVerificationError(1, '[SSL:                          
           CERTIFICATE_VERIFY_FAILED] certificate verify failed:                
           unable to get local issuer certificate                               
           (_ssl.c:1131)')))                                                    
           Finished attempting to scrape: OXO                        base.py:313
</pre>
  

  


  <h2 id="2022-04-16-12-43">2022-04-16</h2>
  <div class="ds-card">
  <div class="ds-card-body">
    <dl class="ds-descriptions">
      <div>
        <dt>Duration</dt>
        <dd>2 seconds</dd>
      </div>
      <div>
        <dt>Start</dt>
        <dd>2022-04-16 12:43:39.937601</dd>
      </div>
      <div>
        <dt>End</dt>
        <dd>2022-04-16 12:43:42.332391</dd>
      </div>
      <div>
        <dt>Status code</dt>
        <dd>1</dd>
      </div>
      <div>
        <dt>Error</dt>
        <dd>Traceback (most recent call last):
  File "/opt/python/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/opt/python/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/opt/python/urllib3/connectionpool.py", line 1040, in _validate_conn
    conn.connect()
  File "/opt/python/urllib3/connection.py", line 416, in connect
    self.sock = ssl_wrap_socket(
  File "/opt/python/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/opt/python/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/var/lang/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/var/lang/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/var/lang/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/python/requests/adapters.py", line 440, in send
    resp = conn.urlopen(
  File "/opt/python/urllib3/connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "/opt/python/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='mycouncil.oxford.gov.uk', port=443): Max retries exceeded with url: /mgWebService.asmx/GetCouncillorsByWard (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/task/lgsf/aws_lambda/handlers.py", line 32, in scraper_worker_handler
    scraper.run(run_log)
  File "/var/task/lgsf/councillors/scrapers.py", line 166, in run
    wards = self.get_councillors()
  File "/var/task/lgsf/councillors/scrapers.py", line 183, in get_councillors
    req = self.get(self.format_councillor_api_url(), verify=self.verify_requests)
  File "/var/task/lgsf/scrapers/base.py", line 46, in get
    response = requests.get(url, headers=headers, verify=verify)
  File "/opt/python/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/opt/python/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/opt/python/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/python/requests/sessions.py", line 667, in send
    history = [resp for resp in gen]
  File "/opt/python/requests/sessions.py", line 667, in <listcomp>
    history = [resp for resp in gen]
  File "/opt/python/requests/sessions.py", line 237, in resolve_redirects
    resp = self.send(
  File "/opt/python/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/opt/python/requests/adapters.py", line 517, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='mycouncil.oxford.gov.uk', port=443): Max retries exceeded with url: /mgWebService.asmx/GetCouncillorsByWard (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))
</dd>
      </div>
    </dl>
  </div>
  </div>

  <h3>Run log</h3>
  <pre>[12:43:39] Fetching Scraper for: OXO                              handlers.py:23
           Begin attempting to scrape: OXO                        handlers.py:27
[12:43:40] Deleting existing data...                                 base.py:228
           Getting all files in OXO...                               base.py:180
           ...found 1 files in OXO                                   base.py:196
           Deleting batch no. 1 consisting of 1 files                base.py:205
[12:43:42] ...data deleted.                                          base.py:235
           Scraping from http://mycouncil.oxford.gov.uk/mgWebService. base.py:40
           asmx/GetCouncillorsByWard                                            
           HTTPSConnectionPool(host='mycouncil.oxford.gov.uk',    handlers.py:36
           port=443): Max retries exceeded with url:                            
           /mgWebService.asmx/GetCouncillorsByWard (Caused by                   
           SSLError(SSLCertVerificationError(1, '[SSL:                          
           CERTIFICATE_VERIFY_FAILED] certificate verify failed:                
           unable to get local issuer certificate                               
           (_ssl.c:1131)')))                                                    
           Finished attempting to scrape: OXO                        base.py:313
</pre>
  

  


  <h2 id="2022-04-15-11-23">2022-04-15</h2>
  <div class="ds-card">
  <div class="ds-card-body">
    <dl class="ds-descriptions">
      <div>
        <dt>Duration</dt>
        <dd>2 seconds</dd>
      </div>
      <div>
        <dt>Start</dt>
        <dd>2022-04-15 11:23:00.534769</dd>
      </div>
      <div>
        <dt>End</dt>
        <dd>2022-04-15 11:23:02.945150</dd>
      </div>
      <div>
        <dt>Status code</dt>
        <dd>1</dd>
      </div>
      <div>
        <dt>Error</dt>
        <dd>Traceback (most recent call last):
  File "/opt/python/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/opt/python/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/opt/python/urllib3/connectionpool.py", line 1040, in _validate_conn
    conn.connect()
  File "/opt/python/urllib3/connection.py", line 416, in connect
    self.sock = ssl_wrap_socket(
  File "/opt/python/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/opt/python/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/var/lang/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/var/lang/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/var/lang/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/python/requests/adapters.py", line 440, in send
    resp = conn.urlopen(
  File "/opt/python/urllib3/connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "/opt/python/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='mycouncil.oxford.gov.uk', port=443): Max retries exceeded with url: /mgWebService.asmx/GetCouncillorsByWard (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/task/lgsf/aws_lambda/handlers.py", line 32, in scraper_worker_handler
    scraper.run(run_log)
  File "/var/task/lgsf/councillors/scrapers.py", line 166, in run
    wards = self.get_councillors()
  File "/var/task/lgsf/councillors/scrapers.py", line 183, in get_councillors
    req = self.get(self.format_councillor_api_url(), verify=self.verify_requests)
  File "/var/task/lgsf/scrapers/base.py", line 46, in get
    response = requests.get(url, headers=headers, verify=verify)
  File "/opt/python/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/opt/python/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/opt/python/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/python/requests/sessions.py", line 667, in send
    history = [resp for resp in gen]
  File "/opt/python/requests/sessions.py", line 667, in <listcomp>
    history = [resp for resp in gen]
  File "/opt/python/requests/sessions.py", line 237, in resolve_redirects
    resp = self.send(
  File "/opt/python/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/opt/python/requests/adapters.py", line 517, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='mycouncil.oxford.gov.uk', port=443): Max retries exceeded with url: /mgWebService.asmx/GetCouncillorsByWard (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))
</dd>
      </div>
    </dl>
  </div>
  </div>

  <h3>Run log</h3>
  <pre>[11:23:00] Fetching Scraper for: OXO                              handlers.py:23
           Begin attempting to scrape: OXO                        handlers.py:27
           Deleting existing data...                                 base.py:228
[11:23:01] Getting all files in OXO...                               base.py:180
           ...found 1 files in OXO                                   base.py:196
           Deleting batch no. 1 consisting of 1 files                base.py:205
[11:23:02] ...data deleted.                                          base.py:235
           Scraping from http://mycouncil.oxford.gov.uk/mgWebService. base.py:40
           asmx/GetCouncillorsByWard                                            
           HTTPSConnectionPool(host='mycouncil.oxford.gov.uk',    handlers.py:36
           port=443): Max retries exceeded with url:                            
           /mgWebService.asmx/GetCouncillorsByWard (Caused by                   
           SSLError(SSLCertVerificationError(1, '[SSL:                          
           CERTIFICATE_VERIFY_FAILED] certificate verify failed:                
           unable to get local issuer certificate                               
           (_ssl.c:1131)')))                                                    
           Finished attempting to scrape: OXO                        base.py:313
</pre>
  


      </main>
      <footer class="ds-footer">...</footer>
    </div>
  </body>
