<!doctype html>
<html>
  <head>
    <title>LGSF Dashboard</title>
    <link rel="stylesheet"  href="/lgsf-dashboard/assets/css/styles.css">
    <link rel="shortcut icon" href="https://democracyclub.org.uk/static/images/logo_icon.png">
  </head>
  <body>
    <div class="ds-page">
      <a class="ds-skip-link" href="#main">skip to content</a>

      <header class="ds-header">
        <a class="ds-skip-link" href="#main">skip to content</a>
        <a class="ds-logo" href="/lgsf-dashboard/">
          <img src="https://DemocracyClub.github.io/design-system/images/logo_icon.svg" alt="" />
          <span>LGSF Logbooks</span>
        </a>

      </header>


      <main id="main" tabindex="-1" class="ds-stack">

        
<style>

    pre {
        height:400px;
        overflow-x: scroll;
        width:100%
    }
</style>




  


  <h2 id="2023-10-22-08-30">2023-10-22</h2>
  <div class="ds-card">
  <div class="ds-card-body">
    <dl class="ds-descriptions">
      <div>
        <dt>Duration</dt>
        <dd>9 seconds</dd>
      </div>
      <div>
        <dt>Start</dt>
        <dd>2023-10-22 08:30:34.038466</dd>
      </div>
      <div>
        <dt>End</dt>
        <dd>2023-10-22 08:30:43.266390</dd>
      </div>
      <div>
        <dt>Status code</dt>
        <dd>0</dd>
      </div>
      <div>
        <dt>Error</dt>
        <dd></dd>
      </div>
    </dl>
  </div>
  </div>

  <h3>Run log</h3>
  <pre>[08:30:34] Fetching Scraper for: CMD                              handlers.py:23
           Begin attempting to scrape: CMD                        handlers.py:27
           Deleting existing data...                                 base.py:239
           Getting all files in Councillors...                       base.py:191
[08:30:35] Getting all files in Councillors/json...                  base.py:191
           ...found 55 files in Councillors/json                     base.py:207
           Getting all files in Councillors/raw...                   base.py:191
           ...found 55 files in Councillors/raw                      base.py:207
           ...found 111 files in Councillors                         base.py:207
           Deleting batch no. 1 consisting of 100 files              base.py:216
[08:30:36] Deleting batch no. 2 consisting of 11 files               base.py:216
[08:30:37] ...data deleted.                                          base.py:246
           Scraping from                                              base.py:42
           https://democracy.camden.gov.uk/mgWebService.asmx/GetCounc           
           illorsByWard                                                         
[08:30:40] Committing batch 1 consisting of 92 files                 base.py:274
[08:30:42] Committing batch 2 consisting of 18 files                 base.py:274
[08:30:43] Finished attempting to scrape: CMD                        base.py:324
</pre>
  

  


  <h2 id="2023-10-21-09-23">2023-10-21</h2>
  <div class="ds-card">
  <div class="ds-card-body">
    <dl class="ds-descriptions">
      <div>
        <dt>Duration</dt>
        <dd>9 seconds</dd>
      </div>
      <div>
        <dt>Start</dt>
        <dd>2023-10-21 09:23:35.618526</dd>
      </div>
      <div>
        <dt>End</dt>
        <dd>2023-10-21 09:23:44.833413</dd>
      </div>
      <div>
        <dt>Status code</dt>
        <dd>0</dd>
      </div>
      <div>
        <dt>Error</dt>
        <dd></dd>
      </div>
    </dl>
  </div>
  </div>

  <h3>Run log</h3>
  <pre>[09:23:35] Fetching Scraper for: CMD                              handlers.py:23
           Begin attempting to scrape: CMD                        handlers.py:27
           Deleting existing data...                                 base.py:239
[09:23:36] Getting all files in Councillors...                       base.py:191
           Getting all files in Councillors/json...                  base.py:191
           ...found 55 files in Councillors/json                     base.py:207
           Getting all files in Councillors/raw...                   base.py:191
[09:23:37] ...found 55 files in Councillors/raw                      base.py:207
           ...found 111 files in Councillors                         base.py:207
           Deleting batch no. 1 consisting of 100 files              base.py:216
           Deleting batch no. 2 consisting of 11 files               base.py:216
[09:23:38] ...data deleted.                                          base.py:246
           Scraping from                                              base.py:42
           https://democracy.camden.gov.uk/mgWebService.asmx/GetCounc           
           illorsByWard                                                         
[09:23:42] Committing batch 1 consisting of 92 files                 base.py:274
[09:23:43] Committing batch 2 consisting of 18 files                 base.py:274
[09:23:44] Finished attempting to scrape: CMD                        base.py:324
</pre>
  

  


  <h2 id="2023-10-20-10-31">2023-10-20</h2>
  <div class="ds-card">
  <div class="ds-card-body">
    <dl class="ds-descriptions">
      <div>
        <dt>Duration</dt>
        <dd>9 seconds</dd>
      </div>
      <div>
        <dt>Start</dt>
        <dd>2023-10-20 10:31:13.303138</dd>
      </div>
      <div>
        <dt>End</dt>
        <dd>2023-10-20 10:31:22.925194</dd>
      </div>
      <div>
        <dt>Status code</dt>
        <dd>0</dd>
      </div>
      <div>
        <dt>Error</dt>
        <dd></dd>
      </div>
    </dl>
  </div>
  </div>

  <h3>Run log</h3>
  <pre>[10:31:13] Fetching Scraper for: CMD                              handlers.py:23
           Begin attempting to scrape: CMD                        handlers.py:27
           Deleting existing data...                                 base.py:239
[10:31:14] Getting all files in Councillors...                       base.py:191
           Getting all files in Councillors/json...                  base.py:191
           ...found 55 files in Councillors/json                     base.py:207
           Getting all files in Councillors/raw...                   base.py:191
           ...found 55 files in Councillors/raw                      base.py:207
           ...found 111 files in Councillors                         base.py:207
           Deleting batch no. 1 consisting of 100 files              base.py:216
[10:31:15] Deleting batch no. 2 consisting of 11 files               base.py:216
[10:31:16] ...data deleted.                                          base.py:246
           Scraping from                                              base.py:42
           https://democracy.camden.gov.uk/mgWebService.asmx/GetCounc           
           illorsByWard                                                         
[10:31:20] Committing batch 1 consisting of 92 files                 base.py:274
[10:31:21] Committing batch 2 consisting of 18 files                 base.py:274
[10:31:22] Finished attempting to scrape: CMD                        base.py:324
</pre>
  

  


  <h2 id="2023-10-19-08-22">2023-10-19</h2>
  <div class="ds-card">
  <div class="ds-card-body">
    <dl class="ds-descriptions">
      <div>
        <dt>Duration</dt>
        <dd>8 seconds</dd>
      </div>
      <div>
        <dt>Start</dt>
        <dd>2023-10-19 08:22:43.165421</dd>
      </div>
      <div>
        <dt>End</dt>
        <dd>2023-10-19 08:22:51.862858</dd>
      </div>
      <div>
        <dt>Status code</dt>
        <dd>0</dd>
      </div>
      <div>
        <dt>Error</dt>
        <dd></dd>
      </div>
    </dl>
  </div>
  </div>

  <h3>Run log</h3>
  <pre>[08:22:43] Fetching Scraper for: CMD                              handlers.py:23
           Begin attempting to scrape: CMD                        handlers.py:27
           Deleting existing data...                                 base.py:239
[08:22:44] Getting all files in Councillors...                       base.py:191
           Getting all files in Councillors/json...                  base.py:191
           ...found 55 files in Councillors/json                     base.py:207
           Getting all files in Councillors/raw...                   base.py:191
           ...found 55 files in Councillors/raw                      base.py:207
           ...found 111 files in Councillors                         base.py:207
           Deleting batch no. 1 consisting of 100 files              base.py:216
[08:22:45] Deleting batch no. 2 consisting of 11 files               base.py:216
[08:22:46] ...data deleted.                                          base.py:246
           Scraping from                                              base.py:42
           https://democracy.camden.gov.uk/mgWebService.asmx/GetCounc           
           illorsByWard                                                         
[08:22:49] Committing batch 1 consisting of 92 files                 base.py:274
[08:22:50] Committing batch 2 consisting of 18 files                 base.py:274
[08:22:51] Finished attempting to scrape: CMD                        base.py:324
</pre>
  

  


  <h2 id="2023-10-18-10-04">2023-10-18</h2>
  <div class="ds-card">
  <div class="ds-card-body">
    <dl class="ds-descriptions">
      <div>
        <dt>Duration</dt>
        <dd>10 seconds</dd>
      </div>
      <div>
        <dt>Start</dt>
        <dd>2023-10-18 10:04:07.186602</dd>
      </div>
      <div>
        <dt>End</dt>
        <dd>2023-10-18 10:04:18.116215</dd>
      </div>
      <div>
        <dt>Status code</dt>
        <dd>0</dd>
      </div>
      <div>
        <dt>Error</dt>
        <dd></dd>
      </div>
    </dl>
  </div>
  </div>

  <h3>Run log</h3>
  <pre>[10:04:07] Fetching Scraper for: CMD                              handlers.py:23
           Begin attempting to scrape: CMD                        handlers.py:27
           Deleting existing data...                                 base.py:239
[10:04:08] Getting all files in Councillors...                       base.py:191
           Getting all files in Councillors/json...                  base.py:191
           ...found 55 files in Councillors/json                     base.py:207
           Getting all files in Councillors/raw...                   base.py:191
           ...found 55 files in Councillors/raw                      base.py:207
           ...found 111 files in Councillors                         base.py:207
           Deleting batch no. 1 consisting of 100 files              base.py:216
[10:04:09] Deleting batch no. 2 consisting of 11 files               base.py:216
[10:04:10] ...data deleted.                                          base.py:246
           Scraping from                                              base.py:42
           https://democracy.camden.gov.uk/mgWebService.asmx/GetCounc           
           illorsByWard                                                         
[10:04:15] Committing batch 1 consisting of 92 files                 base.py:274
[10:04:16] Committing batch 2 consisting of 18 files                 base.py:274
[10:04:18] Finished attempting to scrape: CMD                        base.py:324
</pre>
  

  


  <h2 id="2023-10-17-10-43">2023-10-17</h2>
  <div class="ds-card">
  <div class="ds-card-body">
    <dl class="ds-descriptions">
      <div>
        <dt>Duration</dt>
        <dd>9 seconds</dd>
      </div>
      <div>
        <dt>Start</dt>
        <dd>2023-10-17 10:43:54.388944</dd>
      </div>
      <div>
        <dt>End</dt>
        <dd>2023-10-17 10:44:04.384322</dd>
      </div>
      <div>
        <dt>Status code</dt>
        <dd>0</dd>
      </div>
      <div>
        <dt>Error</dt>
        <dd></dd>
      </div>
    </dl>
  </div>
  </div>

  <h3>Run log</h3>
  <pre>[10:43:54] Fetching Scraper for: CMD                              handlers.py:23
           Begin attempting to scrape: CMD                        handlers.py:27
           Deleting existing data...                                 base.py:239
[10:43:55] Getting all files in Councillors...                       base.py:191
           Getting all files in Councillors/json...                  base.py:191
           ...found 55 files in Councillors/json                     base.py:207
           Getting all files in Councillors/raw...                   base.py:191
           ...found 55 files in Councillors/raw                      base.py:207
           ...found 111 files in Councillors                         base.py:207
           Deleting batch no. 1 consisting of 100 files              base.py:216
[10:43:56] Deleting batch no. 2 consisting of 11 files               base.py:216
[10:43:57] ...data deleted.                                          base.py:246
           Scraping from                                              base.py:42
           https://democracy.camden.gov.uk/mgWebService.asmx/GetCounc           
           illorsByWard                                                         
[10:44:01] Committing batch 1 consisting of 92 files                 base.py:274
[10:44:03] Committing batch 2 consisting of 18 files                 base.py:274
[10:44:04] Finished attempting to scrape: CMD                        base.py:324
</pre>
  

  


  <h2 id="2023-10-16-10-08">2023-10-16</h2>
  <div class="ds-card">
  <div class="ds-card-body">
    <dl class="ds-descriptions">
      <div>
        <dt>Duration</dt>
        <dd>9 seconds</dd>
      </div>
      <div>
        <dt>Start</dt>
        <dd>2023-10-16 10:08:34.894747</dd>
      </div>
      <div>
        <dt>End</dt>
        <dd>2023-10-16 10:08:44.730714</dd>
      </div>
      <div>
        <dt>Status code</dt>
        <dd>0</dd>
      </div>
      <div>
        <dt>Error</dt>
        <dd></dd>
      </div>
    </dl>
  </div>
  </div>

  <h3>Run log</h3>
  <pre>[10:08:34] Fetching Scraper for: CMD                              handlers.py:23
           Begin attempting to scrape: CMD                        handlers.py:27
[10:08:35] Deleting existing data...                                 base.py:239
           Getting all files in Councillors...                       base.py:191
           Getting all files in Councillors/json...                  base.py:191
[10:08:36] ...found 55 files in Councillors/json                     base.py:207
           Getting all files in Councillors/raw...                   base.py:191
           ...found 55 files in Councillors/raw                      base.py:207
           ...found 111 files in Councillors                         base.py:207
           Deleting batch no. 1 consisting of 100 files              base.py:216
[10:08:37] Deleting batch no. 2 consisting of 11 files               base.py:216
           ...data deleted.                                          base.py:246
           Scraping from                                              base.py:42
           https://democracy.camden.gov.uk/mgWebService.asmx/GetCounc           
           illorsByWard                                                         
[10:08:42] Committing batch 1 consisting of 92 files                 base.py:274
[10:08:43] Committing batch 2 consisting of 18 files                 base.py:274
[10:08:44] Finished attempting to scrape: CMD                        base.py:324
</pre>
  

  


  <h2 id="2023-10-15-09-48">2023-10-15</h2>
  <div class="ds-card">
  <div class="ds-card-body">
    <dl class="ds-descriptions">
      <div>
        <dt>Duration</dt>
        <dd>12 seconds</dd>
      </div>
      <div>
        <dt>Start</dt>
        <dd>2023-10-15 09:48:01.412496</dd>
      </div>
      <div>
        <dt>End</dt>
        <dd>2023-10-15 09:48:13.774628</dd>
      </div>
      <div>
        <dt>Status code</dt>
        <dd>0</dd>
      </div>
      <div>
        <dt>Error</dt>
        <dd></dd>
      </div>
    </dl>
  </div>
  </div>

  <h3>Run log</h3>
  <pre>[09:48:01] Fetching Scraper for: CMD                              handlers.py:23
           Begin attempting to scrape: CMD                        handlers.py:27
           Deleting existing data...                                 base.py:239
[09:48:02] Getting all files in Councillors...                       base.py:191
           Getting all files in Councillors/json...                  base.py:191
           ...found 55 files in Councillors/json                     base.py:207
           Getting all files in Councillors/raw...                   base.py:191
           ...found 55 files in Councillors/raw                      base.py:207
           ...found 111 files in Councillors                         base.py:207
[09:48:03] Deleting batch no. 1 consisting of 100 files              base.py:216
           Deleting batch no. 2 consisting of 11 files               base.py:216
[09:48:04] ...data deleted.                                          base.py:246
           Scraping from                                              base.py:42
           https://democracy.camden.gov.uk/mgWebService.asmx/GetCounc           
           illorsByWard                                                         
[09:48:11] Committing batch 1 consisting of 92 files                 base.py:274
[09:48:12] Committing batch 2 consisting of 18 files                 base.py:274
[09:48:13] Finished attempting to scrape: CMD                        base.py:324
</pre>
  

  


  <h2 id="2023-10-14-10-17">2023-10-14</h2>
  <div class="ds-card">
  <div class="ds-card-body">
    <dl class="ds-descriptions">
      <div>
        <dt>Duration</dt>
        <dd>10 seconds</dd>
      </div>
      <div>
        <dt>Start</dt>
        <dd>2023-10-14 10:17:58.312425</dd>
      </div>
      <div>
        <dt>End</dt>
        <dd>2023-10-14 10:18:08.813359</dd>
      </div>
      <div>
        <dt>Status code</dt>
        <dd>0</dd>
      </div>
      <div>
        <dt>Error</dt>
        <dd></dd>
      </div>
    </dl>
  </div>
  </div>

  <h3>Run log</h3>
  <pre>[10:17:58] Fetching Scraper for: CMD                              handlers.py:23
           Begin attempting to scrape: CMD                        handlers.py:27
           Deleting existing data...                                 base.py:239
[10:18:00] Getting all files in Councillors...                       base.py:191
           Getting all files in Councillors/json...                  base.py:191
           ...found 55 files in Councillors/json                     base.py:207
           Getting all files in Councillors/raw...                   base.py:191
           ...found 55 files in Councillors/raw                      base.py:207
           ...found 111 files in Councillors                         base.py:207
           Deleting batch no. 1 consisting of 100 files              base.py:216
[10:18:02] Deleting batch no. 2 consisting of 11 files               base.py:216
           ...data deleted.                                          base.py:246
           Scraping from                                              base.py:42
           https://democracy.camden.gov.uk/mgWebService.asmx/GetCounc           
           illorsByWard                                                         
[10:18:06] Committing batch 1 consisting of 92 files                 base.py:274
[10:18:07] Committing batch 2 consisting of 18 files                 base.py:274
[10:18:08] Finished attempting to scrape: CMD                        base.py:324
</pre>
  

  


  <h2 id="2023-10-13-11-34">2023-10-13</h2>
  <div class="ds-card">
  <div class="ds-card-body">
    <dl class="ds-descriptions">
      <div>
        <dt>Duration</dt>
        <dd>8 seconds</dd>
      </div>
      <div>
        <dt>Start</dt>
        <dd>2023-10-13 11:34:03.399132</dd>
      </div>
      <div>
        <dt>End</dt>
        <dd>2023-10-13 11:34:11.661223</dd>
      </div>
      <div>
        <dt>Status code</dt>
        <dd>0</dd>
      </div>
      <div>
        <dt>Error</dt>
        <dd></dd>
      </div>
    </dl>
  </div>
  </div>

  <h3>Run log</h3>
  <pre>[11:34:03] Fetching Scraper for: CMD                              handlers.py:23
           Begin attempting to scrape: CMD                        handlers.py:27
           Deleting existing data...                                 base.py:239
[11:34:04] Getting all files in Councillors...                       base.py:191
           ...found 1 files in Councillors                           base.py:207
           Deleting batch no. 1 consisting of 1 files                base.py:216
[11:34:05] ...data deleted.                                          base.py:246
           Scraping from                                              base.py:42
           https://democracy.camden.gov.uk/mgWebService.asmx/GetCounc           
           illorsByWard                                                         
[11:34:08] Committing batch 1 consisting of 92 files                 base.py:274
[11:34:10] Committing batch 2 consisting of 18 files                 base.py:274
[11:34:11] Finished attempting to scrape: CMD                        base.py:324
</pre>
  

  


  <h2 id="2023-10-13-08-41">2023-10-13</h2>
  <div class="ds-card">
  <div class="ds-card-body">
    <dl class="ds-descriptions">
      <div>
        <dt>Duration</dt>
        <dd>2 seconds</dd>
      </div>
      <div>
        <dt>Start</dt>
        <dd>2023-10-13 08:41:00.552652</dd>
      </div>
      <div>
        <dt>End</dt>
        <dd>2023-10-13 08:41:02.731218</dd>
      </div>
      <div>
        <dt>Status code</dt>
        <dd>1</dd>
      </div>
      <div>
        <dt>Error</dt>
        <dd>Traceback (most recent call last):
  File "/opt/python/urllib3/connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
  File "/opt/python/urllib3/connectionpool.py", line 403, in _make_request
    self._validate_conn(conn)
  File "/opt/python/urllib3/connectionpool.py", line 1053, in _validate_conn
    conn.connect()
  File "/opt/python/urllib3/connection.py", line 419, in connect
    self.sock = ssl_wrap_socket(
  File "/opt/python/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/opt/python/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/var/lang/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/var/lang/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/var/lang/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/python/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/opt/python/urllib3/connectionpool.py", line 798, in urlopen
    retries = retries.increment(
  File "/opt/python/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='democracy.camden.gov.uk', port=443): Max retries exceeded with url: /mgWebService.asmx/GetCouncillorsByWard (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/task/lgsf/aws_lambda/handlers.py", line 32, in scraper_worker_handler
    scraper.run(run_log)
  File "/var/task/lgsf/councillors/scrapers.py", line 179, in run
    wards = self.get_councillors()
  File "/var/task/lgsf/councillors/scrapers.py", line 196, in get_councillors
    req = self.get(self.format_councillor_api_url(), verify=self.verify_requests)
  File "/var/task/lgsf/scrapers/base.py", line 48, in get
    response = self.requests_session.get(url, headers=headers, verify=verify)
  File "/opt/python/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "/opt/python/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/python/requests/sessions.py", line 725, in send
    history = [resp for resp in gen]
  File "/opt/python/requests/sessions.py", line 725, in <listcomp>
    history = [resp for resp in gen]
  File "/opt/python/requests/sessions.py", line 266, in resolve_redirects
    resp = self.send(
  File "/opt/python/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/opt/python/requests/adapters.py", line 517, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='democracy.camden.gov.uk', port=443): Max retries exceeded with url: /mgWebService.asmx/GetCouncillorsByWard (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))
</dd>
      </div>
    </dl>
  </div>
  </div>

  <h3>Run log</h3>
  <pre>[08:41:00] Fetching Scraper for: CMD                              handlers.py:23
           Begin attempting to scrape: CMD                        handlers.py:27
           Deleting existing data...                                 base.py:239
[08:41:01] Getting all files in Councillors...                       base.py:191
           ...found 1 files in Councillors                           base.py:207
           Deleting batch no. 1 consisting of 1 files                base.py:216
[08:41:02] ...data deleted.                                          base.py:246
           Scraping from                                              base.py:42
           http://democracy.camden.gov.uk/mgWebService.asmx/GetCounci           
           llorsByWard                                                          
           HTTPSConnectionPool(host='democracy.camden.gov.uk',    handlers.py:36
           port=443): Max retries exceeded with url:                            
           /mgWebService.asmx/GetCouncillorsByWard (Caused by                   
           SSLError(SSLCertVerificationError(1, '[SSL:                          
           CERTIFICATE_VERIFY_FAILED] certificate verify failed:                
           unable to get local issuer certificate                               
           (_ssl.c:1131)')))                                                    
           Finished attempting to scrape: CMD                        base.py:324
</pre>
  

  


  <h2 id="2023-10-12-13-08">2023-10-12</h2>
  <div class="ds-card">
  <div class="ds-card-body">
    <dl class="ds-descriptions">
      <div>
        <dt>Duration</dt>
        <dd>2 seconds</dd>
      </div>
      <div>
        <dt>Start</dt>
        <dd>2023-10-12 13:08:35.816599</dd>
      </div>
      <div>
        <dt>End</dt>
        <dd>2023-10-12 13:08:38.131954</dd>
      </div>
      <div>
        <dt>Status code</dt>
        <dd>1</dd>
      </div>
      <div>
        <dt>Error</dt>
        <dd>Traceback (most recent call last):
  File "/opt/python/urllib3/connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
  File "/opt/python/urllib3/connectionpool.py", line 403, in _make_request
    self._validate_conn(conn)
  File "/opt/python/urllib3/connectionpool.py", line 1053, in _validate_conn
    conn.connect()
  File "/opt/python/urllib3/connection.py", line 419, in connect
    self.sock = ssl_wrap_socket(
  File "/opt/python/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/opt/python/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/var/lang/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/var/lang/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/var/lang/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/python/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/opt/python/urllib3/connectionpool.py", line 798, in urlopen
    retries = retries.increment(
  File "/opt/python/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='democracy.camden.gov.uk', port=443): Max retries exceeded with url: /mgWebService.asmx/GetCouncillorsByWard (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/task/lgsf/aws_lambda/handlers.py", line 32, in scraper_worker_handler
    scraper.run(run_log)
  File "/var/task/lgsf/councillors/scrapers.py", line 179, in run
    wards = self.get_councillors()
  File "/var/task/lgsf/councillors/scrapers.py", line 196, in get_councillors
    req = self.get(self.format_councillor_api_url(), verify=self.verify_requests)
  File "/var/task/lgsf/scrapers/base.py", line 48, in get
    response = self.requests_session.get(url, headers=headers, verify=verify)
  File "/opt/python/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "/opt/python/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/python/requests/sessions.py", line 725, in send
    history = [resp for resp in gen]
  File "/opt/python/requests/sessions.py", line 725, in <listcomp>
    history = [resp for resp in gen]
  File "/opt/python/requests/sessions.py", line 266, in resolve_redirects
    resp = self.send(
  File "/opt/python/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/opt/python/requests/adapters.py", line 517, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='democracy.camden.gov.uk', port=443): Max retries exceeded with url: /mgWebService.asmx/GetCouncillorsByWard (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))
</dd>
      </div>
    </dl>
  </div>
  </div>

  <h3>Run log</h3>
  <pre>[13:08:35] Fetching Scraper for: CMD                              handlers.py:23
           Begin attempting to scrape: CMD                        handlers.py:27
[13:08:36] Deleting existing data...                                 base.py:239
           Getting all files in Councillors...                       base.py:191
           ...found 1 files in Councillors                           base.py:207
           Deleting batch no. 1 consisting of 1 files                base.py:216
[13:08:37] ...data deleted.                                          base.py:246
           Scraping from                                              base.py:42
           http://democracy.camden.gov.uk/mgWebService.asmx/GetCounci           
           llorsByWard                                                          
           HTTPSConnectionPool(host='democracy.camden.gov.uk',    handlers.py:36
           port=443): Max retries exceeded with url:                            
           /mgWebService.asmx/GetCouncillorsByWard (Caused by                   
           SSLError(SSLCertVerificationError(1, '[SSL:                          
           CERTIFICATE_VERIFY_FAILED] certificate verify failed:                
           unable to get local issuer certificate                               
           (_ssl.c:1131)')))                                                    
[13:08:38] Finished attempting to scrape: CMD                        base.py:324
</pre>
  

  


  <h2 id="2023-10-11-12-44">2023-10-11</h2>
  <div class="ds-card">
  <div class="ds-card-body">
    <dl class="ds-descriptions">
      <div>
        <dt>Duration</dt>
        <dd>2 seconds</dd>
      </div>
      <div>
        <dt>Start</dt>
        <dd>2023-10-11 12:44:07.025602</dd>
      </div>
      <div>
        <dt>End</dt>
        <dd>2023-10-11 12:44:09.191248</dd>
      </div>
      <div>
        <dt>Status code</dt>
        <dd>1</dd>
      </div>
      <div>
        <dt>Error</dt>
        <dd>Traceback (most recent call last):
  File "/opt/python/urllib3/connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
  File "/opt/python/urllib3/connectionpool.py", line 403, in _make_request
    self._validate_conn(conn)
  File "/opt/python/urllib3/connectionpool.py", line 1053, in _validate_conn
    conn.connect()
  File "/opt/python/urllib3/connection.py", line 419, in connect
    self.sock = ssl_wrap_socket(
  File "/opt/python/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/opt/python/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/var/lang/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/var/lang/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/var/lang/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/python/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/opt/python/urllib3/connectionpool.py", line 798, in urlopen
    retries = retries.increment(
  File "/opt/python/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='democracy.camden.gov.uk', port=443): Max retries exceeded with url: /mgWebService.asmx/GetCouncillorsByWard (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/task/lgsf/aws_lambda/handlers.py", line 32, in scraper_worker_handler
    scraper.run(run_log)
  File "/var/task/lgsf/councillors/scrapers.py", line 179, in run
    wards = self.get_councillors()
  File "/var/task/lgsf/councillors/scrapers.py", line 196, in get_councillors
    req = self.get(self.format_councillor_api_url(), verify=self.verify_requests)
  File "/var/task/lgsf/scrapers/base.py", line 48, in get
    response = self.requests_session.get(url, headers=headers, verify=verify)
  File "/opt/python/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "/opt/python/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/python/requests/sessions.py", line 725, in send
    history = [resp for resp in gen]
  File "/opt/python/requests/sessions.py", line 725, in <listcomp>
    history = [resp for resp in gen]
  File "/opt/python/requests/sessions.py", line 266, in resolve_redirects
    resp = self.send(
  File "/opt/python/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/opt/python/requests/adapters.py", line 517, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='democracy.camden.gov.uk', port=443): Max retries exceeded with url: /mgWebService.asmx/GetCouncillorsByWard (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))
</dd>
      </div>
    </dl>
  </div>
  </div>

  <h3>Run log</h3>
  <pre>[12:44:07] Fetching Scraper for: CMD                              handlers.py:23
           Begin attempting to scrape: CMD                        handlers.py:27
           Deleting existing data...                                 base.py:239
           Getting all files in Councillors...                       base.py:191
[12:44:08] ...found 1 files in Councillors                           base.py:207
           Deleting batch no. 1 consisting of 1 files                base.py:216
           ...data deleted.                                          base.py:246
           Scraping from                                              base.py:42
           http://democracy.camden.gov.uk/mgWebService.asmx/GetCounci           
           llorsByWard                                                          
           HTTPSConnectionPool(host='democracy.camden.gov.uk',    handlers.py:36
           port=443): Max retries exceeded with url:                            
           /mgWebService.asmx/GetCouncillorsByWard (Caused by                   
           SSLError(SSLCertVerificationError(1, '[SSL:                          
           CERTIFICATE_VERIFY_FAILED] certificate verify failed:                
           unable to get local issuer certificate                               
           (_ssl.c:1131)')))                                                    
[12:44:09] Finished attempting to scrape: CMD                        base.py:324
</pre>
  

  


  <h2 id="2023-10-10-12-36">2023-10-10</h2>
  <div class="ds-card">
  <div class="ds-card-body">
    <dl class="ds-descriptions">
      <div>
        <dt>Duration</dt>
        <dd>2 seconds</dd>
      </div>
      <div>
        <dt>Start</dt>
        <dd>2023-10-10 12:36:17.467935</dd>
      </div>
      <div>
        <dt>End</dt>
        <dd>2023-10-10 12:36:19.738615</dd>
      </div>
      <div>
        <dt>Status code</dt>
        <dd>1</dd>
      </div>
      <div>
        <dt>Error</dt>
        <dd>Traceback (most recent call last):
  File "/opt/python/urllib3/connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
  File "/opt/python/urllib3/connectionpool.py", line 403, in _make_request
    self._validate_conn(conn)
  File "/opt/python/urllib3/connectionpool.py", line 1053, in _validate_conn
    conn.connect()
  File "/opt/python/urllib3/connection.py", line 419, in connect
    self.sock = ssl_wrap_socket(
  File "/opt/python/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/opt/python/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/var/lang/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/var/lang/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/var/lang/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/python/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/opt/python/urllib3/connectionpool.py", line 798, in urlopen
    retries = retries.increment(
  File "/opt/python/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='democracy.camden.gov.uk', port=443): Max retries exceeded with url: /mgWebService.asmx/GetCouncillorsByWard (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/task/lgsf/aws_lambda/handlers.py", line 32, in scraper_worker_handler
    scraper.run(run_log)
  File "/var/task/lgsf/councillors/scrapers.py", line 179, in run
    wards = self.get_councillors()
  File "/var/task/lgsf/councillors/scrapers.py", line 196, in get_councillors
    req = self.get(self.format_councillor_api_url(), verify=self.verify_requests)
  File "/var/task/lgsf/scrapers/base.py", line 48, in get
    response = self.requests_session.get(url, headers=headers, verify=verify)
  File "/opt/python/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "/opt/python/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/python/requests/sessions.py", line 725, in send
    history = [resp for resp in gen]
  File "/opt/python/requests/sessions.py", line 725, in <listcomp>
    history = [resp for resp in gen]
  File "/opt/python/requests/sessions.py", line 266, in resolve_redirects
    resp = self.send(
  File "/opt/python/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/opt/python/requests/adapters.py", line 517, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='democracy.camden.gov.uk', port=443): Max retries exceeded with url: /mgWebService.asmx/GetCouncillorsByWard (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))
</dd>
      </div>
    </dl>
  </div>
  </div>

  <h3>Run log</h3>
  <pre>[12:36:17] Fetching Scraper for: CMD                              handlers.py:23
           Begin attempting to scrape: CMD                        handlers.py:27
           Deleting existing data...                                 base.py:239
[12:36:18] Getting all files in Councillors...                       base.py:191
           ...found 1 files in Councillors                           base.py:207
           Deleting batch no. 1 consisting of 1 files                base.py:216
[12:36:19] ...data deleted.                                          base.py:246
           Scraping from                                              base.py:42
           http://democracy.camden.gov.uk/mgWebService.asmx/GetCounci           
           llorsByWard                                                          
           HTTPSConnectionPool(host='democracy.camden.gov.uk',    handlers.py:36
           port=443): Max retries exceeded with url:                            
           /mgWebService.asmx/GetCouncillorsByWard (Caused by                   
           SSLError(SSLCertVerificationError(1, '[SSL:                          
           CERTIFICATE_VERIFY_FAILED] certificate verify failed:                
           unable to get local issuer certificate                               
           (_ssl.c:1131)')))                                                    
           Finished attempting to scrape: CMD                        base.py:324
</pre>
  

  


  <h2 id="2023-10-09-12-21">2023-10-09</h2>
  <div class="ds-card">
  <div class="ds-card-body">
    <dl class="ds-descriptions">
      <div>
        <dt>Duration</dt>
        <dd>2 seconds</dd>
      </div>
      <div>
        <dt>Start</dt>
        <dd>2023-10-09 12:21:15.578630</dd>
      </div>
      <div>
        <dt>End</dt>
        <dd>2023-10-09 12:21:17.865930</dd>
      </div>
      <div>
        <dt>Status code</dt>
        <dd>1</dd>
      </div>
      <div>
        <dt>Error</dt>
        <dd>Traceback (most recent call last):
  File "/opt/python/urllib3/connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
  File "/opt/python/urllib3/connectionpool.py", line 403, in _make_request
    self._validate_conn(conn)
  File "/opt/python/urllib3/connectionpool.py", line 1053, in _validate_conn
    conn.connect()
  File "/opt/python/urllib3/connection.py", line 419, in connect
    self.sock = ssl_wrap_socket(
  File "/opt/python/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/opt/python/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/var/lang/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/var/lang/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/var/lang/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/python/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/opt/python/urllib3/connectionpool.py", line 798, in urlopen
    retries = retries.increment(
  File "/opt/python/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='democracy.camden.gov.uk', port=443): Max retries exceeded with url: /mgWebService.asmx/GetCouncillorsByWard (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/task/lgsf/aws_lambda/handlers.py", line 32, in scraper_worker_handler
    scraper.run(run_log)
  File "/var/task/lgsf/councillors/scrapers.py", line 179, in run
    wards = self.get_councillors()
  File "/var/task/lgsf/councillors/scrapers.py", line 196, in get_councillors
    req = self.get(self.format_councillor_api_url(), verify=self.verify_requests)
  File "/var/task/lgsf/scrapers/base.py", line 48, in get
    response = self.requests_session.get(url, headers=headers, verify=verify)
  File "/opt/python/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "/opt/python/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/python/requests/sessions.py", line 725, in send
    history = [resp for resp in gen]
  File "/opt/python/requests/sessions.py", line 725, in <listcomp>
    history = [resp for resp in gen]
  File "/opt/python/requests/sessions.py", line 266, in resolve_redirects
    resp = self.send(
  File "/opt/python/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/opt/python/requests/adapters.py", line 517, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='democracy.camden.gov.uk', port=443): Max retries exceeded with url: /mgWebService.asmx/GetCouncillorsByWard (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))
</dd>
      </div>
    </dl>
  </div>
  </div>

  <h3>Run log</h3>
  <pre>[12:21:15] Fetching Scraper for: CMD                              handlers.py:23
           Begin attempting to scrape: CMD                        handlers.py:27
           Deleting existing data...                                 base.py:239
[12:21:16] Getting all files in Councillors...                       base.py:191
           ...found 1 files in Councillors                           base.py:207
           Deleting batch no. 1 consisting of 1 files                base.py:216
[12:21:17] ...data deleted.                                          base.py:246
           Scraping from                                              base.py:42
           http://democracy.camden.gov.uk/mgWebService.asmx/GetCounci           
           llorsByWard                                                          
           HTTPSConnectionPool(host='democracy.camden.gov.uk',    handlers.py:36
           port=443): Max retries exceeded with url:                            
           /mgWebService.asmx/GetCouncillorsByWard (Caused by                   
           SSLError(SSLCertVerificationError(1, '[SSL:                          
           CERTIFICATE_VERIFY_FAILED] certificate verify failed:                
           unable to get local issuer certificate                               
           (_ssl.c:1131)')))                                                    
           Finished attempting to scrape: CMD                        base.py:324
</pre>
  

  


  <h2 id="2023-10-08-14-15">2023-10-08</h2>
  <div class="ds-card">
  <div class="ds-card-body">
    <dl class="ds-descriptions">
      <div>
        <dt>Duration</dt>
        <dd>2 seconds</dd>
      </div>
      <div>
        <dt>Start</dt>
        <dd>2023-10-08 14:15:06.666211</dd>
      </div>
      <div>
        <dt>End</dt>
        <dd>2023-10-08 14:15:08.890950</dd>
      </div>
      <div>
        <dt>Status code</dt>
        <dd>1</dd>
      </div>
      <div>
        <dt>Error</dt>
        <dd>Traceback (most recent call last):
  File "/opt/python/urllib3/connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
  File "/opt/python/urllib3/connectionpool.py", line 403, in _make_request
    self._validate_conn(conn)
  File "/opt/python/urllib3/connectionpool.py", line 1053, in _validate_conn
    conn.connect()
  File "/opt/python/urllib3/connection.py", line 419, in connect
    self.sock = ssl_wrap_socket(
  File "/opt/python/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/opt/python/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/var/lang/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/var/lang/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/var/lang/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/python/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/opt/python/urllib3/connectionpool.py", line 798, in urlopen
    retries = retries.increment(
  File "/opt/python/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='democracy.camden.gov.uk', port=443): Max retries exceeded with url: /mgWebService.asmx/GetCouncillorsByWard (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/task/lgsf/aws_lambda/handlers.py", line 32, in scraper_worker_handler
    scraper.run(run_log)
  File "/var/task/lgsf/councillors/scrapers.py", line 179, in run
    wards = self.get_councillors()
  File "/var/task/lgsf/councillors/scrapers.py", line 196, in get_councillors
    req = self.get(self.format_councillor_api_url(), verify=self.verify_requests)
  File "/var/task/lgsf/scrapers/base.py", line 48, in get
    response = self.requests_session.get(url, headers=headers, verify=verify)
  File "/opt/python/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "/opt/python/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/python/requests/sessions.py", line 725, in send
    history = [resp for resp in gen]
  File "/opt/python/requests/sessions.py", line 725, in <listcomp>
    history = [resp for resp in gen]
  File "/opt/python/requests/sessions.py", line 266, in resolve_redirects
    resp = self.send(
  File "/opt/python/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/opt/python/requests/adapters.py", line 517, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='democracy.camden.gov.uk', port=443): Max retries exceeded with url: /mgWebService.asmx/GetCouncillorsByWard (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))
</dd>
      </div>
    </dl>
  </div>
  </div>

  <h3>Run log</h3>
  <pre>[14:15:06] Fetching Scraper for: CMD                              handlers.py:23
           Begin attempting to scrape: CMD                        handlers.py:27
           Deleting existing data...                                 base.py:239
[14:15:07] Getting all files in Councillors...                       base.py:191
           ...found 1 files in Councillors                           base.py:207
           Deleting batch no. 1 consisting of 1 files                base.py:216
[14:15:08] ...data deleted.                                          base.py:246
           Scraping from                                              base.py:42
           http://democracy.camden.gov.uk/mgWebService.asmx/GetCounci           
           llorsByWard                                                          
           HTTPSConnectionPool(host='democracy.camden.gov.uk',    handlers.py:36
           port=443): Max retries exceeded with url:                            
           /mgWebService.asmx/GetCouncillorsByWard (Caused by                   
           SSLError(SSLCertVerificationError(1, '[SSL:                          
           CERTIFICATE_VERIFY_FAILED] certificate verify failed:                
           unable to get local issuer certificate                               
           (_ssl.c:1131)')))                                                    
           Finished attempting to scrape: CMD                        base.py:324
</pre>
  

  


  <h2 id="2023-10-07-14-06">2023-10-07</h2>
  <div class="ds-card">
  <div class="ds-card-body">
    <dl class="ds-descriptions">
      <div>
        <dt>Duration</dt>
        <dd>1 seconds</dd>
      </div>
      <div>
        <dt>Start</dt>
        <dd>2023-10-07 14:06:38.663876</dd>
      </div>
      <div>
        <dt>End</dt>
        <dd>2023-10-07 14:06:40.621535</dd>
      </div>
      <div>
        <dt>Status code</dt>
        <dd>1</dd>
      </div>
      <div>
        <dt>Error</dt>
        <dd>Traceback (most recent call last):
  File "/opt/python/urllib3/connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
  File "/opt/python/urllib3/connectionpool.py", line 403, in _make_request
    self._validate_conn(conn)
  File "/opt/python/urllib3/connectionpool.py", line 1053, in _validate_conn
    conn.connect()
  File "/opt/python/urllib3/connection.py", line 419, in connect
    self.sock = ssl_wrap_socket(
  File "/opt/python/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/opt/python/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/var/lang/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/var/lang/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/var/lang/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/python/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/opt/python/urllib3/connectionpool.py", line 798, in urlopen
    retries = retries.increment(
  File "/opt/python/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='democracy.camden.gov.uk', port=443): Max retries exceeded with url: /mgWebService.asmx/GetCouncillorsByWard (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/task/lgsf/aws_lambda/handlers.py", line 32, in scraper_worker_handler
    scraper.run(run_log)
  File "/var/task/lgsf/councillors/scrapers.py", line 179, in run
    wards = self.get_councillors()
  File "/var/task/lgsf/councillors/scrapers.py", line 196, in get_councillors
    req = self.get(self.format_councillor_api_url(), verify=self.verify_requests)
  File "/var/task/lgsf/scrapers/base.py", line 48, in get
    response = self.requests_session.get(url, headers=headers, verify=verify)
  File "/opt/python/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "/opt/python/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/python/requests/sessions.py", line 725, in send
    history = [resp for resp in gen]
  File "/opt/python/requests/sessions.py", line 725, in <listcomp>
    history = [resp for resp in gen]
  File "/opt/python/requests/sessions.py", line 266, in resolve_redirects
    resp = self.send(
  File "/opt/python/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/opt/python/requests/adapters.py", line 517, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='democracy.camden.gov.uk', port=443): Max retries exceeded with url: /mgWebService.asmx/GetCouncillorsByWard (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))
</dd>
      </div>
    </dl>
  </div>
  </div>

  <h3>Run log</h3>
  <pre>[14:06:38] Fetching Scraper for: CMD                              handlers.py:23
           Begin attempting to scrape: CMD                        handlers.py:27
           Deleting existing data...                                 base.py:239
[14:06:39] Getting all files in Councillors...                       base.py:191
           ...found 1 files in Councillors                           base.py:207
           Deleting batch no. 1 consisting of 1 files                base.py:216
[14:06:40] ...data deleted.                                          base.py:246
           Scraping from                                              base.py:42
           http://democracy.camden.gov.uk/mgWebService.asmx/GetCounci           
           llorsByWard                                                          
           HTTPSConnectionPool(host='democracy.camden.gov.uk',    handlers.py:36
           port=443): Max retries exceeded with url:                            
           /mgWebService.asmx/GetCouncillorsByWard (Caused by                   
           SSLError(SSLCertVerificationError(1, '[SSL:                          
           CERTIFICATE_VERIFY_FAILED] certificate verify failed:                
           unable to get local issuer certificate                               
           (_ssl.c:1131)')))                                                    
           Finished attempting to scrape: CMD                        base.py:324
</pre>
  

  


  <h2 id="2023-10-06-12-34">2023-10-06</h2>
  <div class="ds-card">
  <div class="ds-card-body">
    <dl class="ds-descriptions">
      <div>
        <dt>Duration</dt>
        <dd>2 seconds</dd>
      </div>
      <div>
        <dt>Start</dt>
        <dd>2023-10-06 12:34:24.463246</dd>
      </div>
      <div>
        <dt>End</dt>
        <dd>2023-10-06 12:34:26.755669</dd>
      </div>
      <div>
        <dt>Status code</dt>
        <dd>1</dd>
      </div>
      <div>
        <dt>Error</dt>
        <dd>Traceback (most recent call last):
  File "/opt/python/urllib3/connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
  File "/opt/python/urllib3/connectionpool.py", line 403, in _make_request
    self._validate_conn(conn)
  File "/opt/python/urllib3/connectionpool.py", line 1053, in _validate_conn
    conn.connect()
  File "/opt/python/urllib3/connection.py", line 419, in connect
    self.sock = ssl_wrap_socket(
  File "/opt/python/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/opt/python/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/var/lang/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/var/lang/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/var/lang/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/python/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/opt/python/urllib3/connectionpool.py", line 798, in urlopen
    retries = retries.increment(
  File "/opt/python/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='democracy.camden.gov.uk', port=443): Max retries exceeded with url: /mgWebService.asmx/GetCouncillorsByWard (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/task/lgsf/aws_lambda/handlers.py", line 32, in scraper_worker_handler
    scraper.run(run_log)
  File "/var/task/lgsf/councillors/scrapers.py", line 179, in run
    wards = self.get_councillors()
  File "/var/task/lgsf/councillors/scrapers.py", line 196, in get_councillors
    req = self.get(self.format_councillor_api_url(), verify=self.verify_requests)
  File "/var/task/lgsf/scrapers/base.py", line 48, in get
    response = self.requests_session.get(url, headers=headers, verify=verify)
  File "/opt/python/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "/opt/python/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/python/requests/sessions.py", line 725, in send
    history = [resp for resp in gen]
  File "/opt/python/requests/sessions.py", line 725, in <listcomp>
    history = [resp for resp in gen]
  File "/opt/python/requests/sessions.py", line 266, in resolve_redirects
    resp = self.send(
  File "/opt/python/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/opt/python/requests/adapters.py", line 517, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='democracy.camden.gov.uk', port=443): Max retries exceeded with url: /mgWebService.asmx/GetCouncillorsByWard (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))
</dd>
      </div>
    </dl>
  </div>
  </div>

  <h3>Run log</h3>
  <pre>[12:34:24] Fetching Scraper for: CMD                              handlers.py:23
           Begin attempting to scrape: CMD                        handlers.py:27
           Deleting existing data...                                 base.py:239
[12:34:25] Getting all files in Councillors...                       base.py:191
           ...found 1 files in Councillors                           base.py:207
           Deleting batch no. 1 consisting of 1 files                base.py:216
[12:34:26] ...data deleted.                                          base.py:246
           Scraping from                                              base.py:42
           http://democracy.camden.gov.uk/mgWebService.asmx/GetCounci           
           llorsByWard                                                          
           HTTPSConnectionPool(host='democracy.camden.gov.uk',    handlers.py:36
           port=443): Max retries exceeded with url:                            
           /mgWebService.asmx/GetCouncillorsByWard (Caused by                   
           SSLError(SSLCertVerificationError(1, '[SSL:                          
           CERTIFICATE_VERIFY_FAILED] certificate verify failed:                
           unable to get local issuer certificate                               
           (_ssl.c:1131)')))                                                    
           Finished attempting to scrape: CMD                        base.py:324
</pre>
  

  


  <h2 id="2023-10-05-13-03">2023-10-05</h2>
  <div class="ds-card">
  <div class="ds-card-body">
    <dl class="ds-descriptions">
      <div>
        <dt>Duration</dt>
        <dd>2 seconds</dd>
      </div>
      <div>
        <dt>Start</dt>
        <dd>2023-10-05 13:03:10.423616</dd>
      </div>
      <div>
        <dt>End</dt>
        <dd>2023-10-05 13:03:12.695249</dd>
      </div>
      <div>
        <dt>Status code</dt>
        <dd>1</dd>
      </div>
      <div>
        <dt>Error</dt>
        <dd>Traceback (most recent call last):
  File "/opt/python/urllib3/connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
  File "/opt/python/urllib3/connectionpool.py", line 403, in _make_request
    self._validate_conn(conn)
  File "/opt/python/urllib3/connectionpool.py", line 1053, in _validate_conn
    conn.connect()
  File "/opt/python/urllib3/connection.py", line 419, in connect
    self.sock = ssl_wrap_socket(
  File "/opt/python/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/opt/python/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/var/lang/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/var/lang/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/var/lang/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/python/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/opt/python/urllib3/connectionpool.py", line 798, in urlopen
    retries = retries.increment(
  File "/opt/python/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='democracy.camden.gov.uk', port=443): Max retries exceeded with url: /mgWebService.asmx/GetCouncillorsByWard (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/task/lgsf/aws_lambda/handlers.py", line 32, in scraper_worker_handler
    scraper.run(run_log)
  File "/var/task/lgsf/councillors/scrapers.py", line 179, in run
    wards = self.get_councillors()
  File "/var/task/lgsf/councillors/scrapers.py", line 196, in get_councillors
    req = self.get(self.format_councillor_api_url(), verify=self.verify_requests)
  File "/var/task/lgsf/scrapers/base.py", line 48, in get
    response = self.requests_session.get(url, headers=headers, verify=verify)
  File "/opt/python/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "/opt/python/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/python/requests/sessions.py", line 725, in send
    history = [resp for resp in gen]
  File "/opt/python/requests/sessions.py", line 725, in <listcomp>
    history = [resp for resp in gen]
  File "/opt/python/requests/sessions.py", line 266, in resolve_redirects
    resp = self.send(
  File "/opt/python/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/opt/python/requests/adapters.py", line 517, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='democracy.camden.gov.uk', port=443): Max retries exceeded with url: /mgWebService.asmx/GetCouncillorsByWard (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))
</dd>
      </div>
    </dl>
  </div>
  </div>

  <h3>Run log</h3>
  <pre>[13:03:10] Fetching Scraper for: CMD                              handlers.py:23
           Begin attempting to scrape: CMD                        handlers.py:27
           Deleting existing data...                                 base.py:239
[13:03:11] Getting all files in Councillors...                       base.py:191
           ...found 1 files in Councillors                           base.py:207
           Deleting batch no. 1 consisting of 1 files                base.py:216
[13:03:12] ...data deleted.                                          base.py:246
           Scraping from                                              base.py:42
           http://democracy.camden.gov.uk/mgWebService.asmx/GetCounci           
           llorsByWard                                                          
           HTTPSConnectionPool(host='democracy.camden.gov.uk',    handlers.py:36
           port=443): Max retries exceeded with url:                            
           /mgWebService.asmx/GetCouncillorsByWard (Caused by                   
           SSLError(SSLCertVerificationError(1, '[SSL:                          
           CERTIFICATE_VERIFY_FAILED] certificate verify failed:                
           unable to get local issuer certificate                               
           (_ssl.c:1131)')))                                                    
           Finished attempting to scrape: CMD                        base.py:324
</pre>
  

  


  <h2 id="2023-10-04-12-26">2023-10-04</h2>
  <div class="ds-card">
  <div class="ds-card-body">
    <dl class="ds-descriptions">
      <div>
        <dt>Duration</dt>
        <dd>2 seconds</dd>
      </div>
      <div>
        <dt>Start</dt>
        <dd>2023-10-04 12:26:25.694064</dd>
      </div>
      <div>
        <dt>End</dt>
        <dd>2023-10-04 12:26:27.840859</dd>
      </div>
      <div>
        <dt>Status code</dt>
        <dd>1</dd>
      </div>
      <div>
        <dt>Error</dt>
        <dd>Traceback (most recent call last):
  File "/opt/python/urllib3/connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
  File "/opt/python/urllib3/connectionpool.py", line 403, in _make_request
    self._validate_conn(conn)
  File "/opt/python/urllib3/connectionpool.py", line 1053, in _validate_conn
    conn.connect()
  File "/opt/python/urllib3/connection.py", line 419, in connect
    self.sock = ssl_wrap_socket(
  File "/opt/python/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/opt/python/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/var/lang/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/var/lang/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/var/lang/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/python/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/opt/python/urllib3/connectionpool.py", line 798, in urlopen
    retries = retries.increment(
  File "/opt/python/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='democracy.camden.gov.uk', port=443): Max retries exceeded with url: /mgWebService.asmx/GetCouncillorsByWard (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/task/lgsf/aws_lambda/handlers.py", line 32, in scraper_worker_handler
    scraper.run(run_log)
  File "/var/task/lgsf/councillors/scrapers.py", line 179, in run
    wards = self.get_councillors()
  File "/var/task/lgsf/councillors/scrapers.py", line 196, in get_councillors
    req = self.get(self.format_councillor_api_url(), verify=self.verify_requests)
  File "/var/task/lgsf/scrapers/base.py", line 48, in get
    response = self.requests_session.get(url, headers=headers, verify=verify)
  File "/opt/python/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "/opt/python/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/python/requests/sessions.py", line 725, in send
    history = [resp for resp in gen]
  File "/opt/python/requests/sessions.py", line 725, in <listcomp>
    history = [resp for resp in gen]
  File "/opt/python/requests/sessions.py", line 266, in resolve_redirects
    resp = self.send(
  File "/opt/python/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/opt/python/requests/adapters.py", line 517, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='democracy.camden.gov.uk', port=443): Max retries exceeded with url: /mgWebService.asmx/GetCouncillorsByWard (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))
</dd>
      </div>
    </dl>
  </div>
  </div>

  <h3>Run log</h3>
  <pre>[12:26:25] Fetching Scraper for: CMD                              handlers.py:23
           Begin attempting to scrape: CMD                        handlers.py:27
[12:26:26] Deleting existing data...                                 base.py:239
           Getting all files in Councillors...                       base.py:191
           ...found 1 files in Councillors                           base.py:207
           Deleting batch no. 1 consisting of 1 files                base.py:216
[12:26:27] ...data deleted.                                          base.py:246
           Scraping from                                              base.py:42
           http://democracy.camden.gov.uk/mgWebService.asmx/GetCounci           
           llorsByWard                                                          
           HTTPSConnectionPool(host='democracy.camden.gov.uk',    handlers.py:36
           port=443): Max retries exceeded with url:                            
           /mgWebService.asmx/GetCouncillorsByWard (Caused by                   
           SSLError(SSLCertVerificationError(1, '[SSL:                          
           CERTIFICATE_VERIFY_FAILED] certificate verify failed:                
           unable to get local issuer certificate                               
           (_ssl.c:1131)')))                                                    
           Finished attempting to scrape: CMD                        base.py:324
</pre>
  


      </main>
      <footer class="ds-footer">
        <div class="ds-block-centered ds-text-centered ds-stack">
          <div class="ds-cluster-center">
            <ul>
              <li><a href="/lgsf-dashboard/api/failing.json">Failing JSON</a></li>
            </ul>
          </div>
          <div class="ds-copyright">
            <a href="https://democracyclub.org.uk/">
              <img src="https://DemocracyClub.github.io/design-system/images/logo_white_text.svg" alt="Democracy Club Home" />
            </a>
            <p>Copyright © 2021 Democracy Club</p>
            <p>Community Interest Company</p>
            <p>Company No: <a href="https://beta.companieshouse.gov.uk/company/09461226">09461226</a></p>
          </div>
        </div>
      </footer>
    </div>
  </body>
