<!doctype html>
<html>
  <head>
    <title>Page title</title>
    <link rel="stylesheet"  href="/lgsf-dashboard/assets/css/styles.css">
    <style>



    </style>

  </head>
  <body>



    <div class="ds-page">
      <a class="ds-skip-link" href="#main">skip to content</a>

      <header class="ds-header">
        <a class="ds-skip-link" href="#main">skip to content</a>
        <a class="ds-logo" href="/lgsf-dashboard/">
          <img src="https://DemocracyClub.github.io/design-system/images/logo_icon.svg" alt="" />
          <span>LGSF Logbooks</span>
        </a>

      </header>


      <main id="main" tabindex="-1" class="ds-stack">

        
<style>

    pre {
        height:400px;
        overflow-x: scroll;
        width:100%
    }
</style>




  <h2 id="2022-03-13-00-05">2022-03-13</h2>
  <div class="ds-card">
  <div class="ds-card-body">
    <dl class="ds-descriptions">
      <div>
        <dt>Duration</dt>
        <dd>8 seconds</dd>
      </div>
      <div>
        <dt>Start</dt>
        <dd>2022-03-13 00:05:53.921646</dd>
      </div>
      <div>
        <dt>End</dt>
        <dd>2022-03-13 00:06:02.880761</dd>
      </div>
      <div>
        <dt>Status code</dt>
        <dd>200</dd>
      </div>
      <div>
        <dt>Error</dt>
        <dd>An error occurred (ThrottlingException) when calling the CreateCommit operation (reached max retries: 4): Rate exceeded</dd>
      </div>
    </dl>
  </div>
  </div>

  <h3>Run log</h3>
  <pre>[00:06:02] An error occurred (ThrottlingException) when calling   handlers.py:34
           the CreateCommit operation (reached max retries: 4):                 
           Rate exceeded                                                        
           Finished attempting to scrape: ZET                        base.py:319
</pre>

  <h2 id="2022-03-12-11-27">2022-03-12</h2>
  <div class="ds-card">
  <div class="ds-card-body">
    <dl class="ds-descriptions">
      <div>
        <dt>Duration</dt>
        <dd>6 seconds</dd>
      </div>
      <div>
        <dt>Start</dt>
        <dd>2022-03-12 11:27:27.827200</dd>
      </div>
      <div>
        <dt>End</dt>
        <dd>2022-03-12 11:27:34.294594</dd>
      </div>
      <div>
        <dt>Status code</dt>
        <dd>200</dd>
      </div>
      <div>
        <dt>Error</dt>
        <dd></dd>
      </div>
    </dl>
  </div>
  </div>

  <h3>Run log</h3>
  <pre>[11:27:27] Fetching Scraper for: ZET                              handlers.py:22
           Begin attempting to scrape: ZET                        handlers.py:25
           Deleting existing data...                                 base.py:234
[11:27:28] Getting all files in ZET...                               base.py:186
           ...found 1 files in ZET                                   base.py:202
           Deleting batch no. 1 consisting of 1 files                base.py:211
[11:27:32] ...data deleted.                                          base.py:241
           Scraping from                                              base.py:40
           http://www.shetland.gov.uk/about_your_councillors/                   
[11:27:34] Finished attempting to scrape: ZET                        base.py:319
</pre>

  <h2 id="2022-03-11-11-28">2022-03-11</h2>
  <div class="ds-card">
  <div class="ds-card-body">
    <dl class="ds-descriptions">
      <div>
        <dt>Duration</dt>
        <dd>5 seconds</dd>
      </div>
      <div>
        <dt>Start</dt>
        <dd>2022-03-11 11:28:59.206172</dd>
      </div>
      <div>
        <dt>End</dt>
        <dd>2022-03-11 11:29:05.041241</dd>
      </div>
      <div>
        <dt>Status code</dt>
        <dd></dd>
      </div>
      <div>
        <dt>Error</dt>
        <dd>An error occurred (ThrottlingException) when calling the CreateCommit operation (reached max retries: 4): Rate exceeded</dd>
      </div>
    </dl>
  </div>
  </div>

  <h3>Run log</h3>
  <pre>[11:28:59] Fetching Scraper for: ZET                              handlers.py:22
           Begin attempting to scrape: ZET                        handlers.py:25
           Deleting existing data...                                 base.py:234
           Getting all files in ZET...                               base.py:186
[11:29:00] ...found 1 files in ZET                                   base.py:202
           Deleting batch no. 1 consisting of 1 files                base.py:211
[11:29:04] An error occurred (ThrottlingException) when calling   handlers.py:34
           the CreateCommit operation (reached max retries: 4):                 
           Rate exceeded                                                        
[11:29:05] No new councillor data found.                             base.py:317
           Finished attempting to scrape: ZET                        base.py:319
</pre>

  <h2 id="2022-03-10-11-20">2022-03-10</h2>
  <div class="ds-card">
  <div class="ds-card-body">
    <dl class="ds-descriptions">
      <div>
        <dt>Duration</dt>
        <dd>7 seconds</dd>
      </div>
      <div>
        <dt>Start</dt>
        <dd>2022-03-10 11:20:24.465717</dd>
      </div>
      <div>
        <dt>End</dt>
        <dd>2022-03-10 11:20:32.095445</dd>
      </div>
      <div>
        <dt>Status code</dt>
        <dd></dd>
      </div>
      <div>
        <dt>Error</dt>
        <dd>An error occurred (ThrottlingException) when calling the CreateCommit operation (reached max retries: 4): Rate exceeded</dd>
      </div>
    </dl>
  </div>
  </div>

  <h3>Run log</h3>
  <pre>[11:20:24] Fetching Scraper for: ZET                              handlers.py:22
           Begin attempting to scrape: ZET                        handlers.py:25
           Deleting existing data...                                 base.py:234
[11:20:25] Getting all files in ZET...                               base.py:186
           ...found 1 files in ZET                                   base.py:202
           Deleting batch no. 1 consisting of 1 files                base.py:211
[11:20:31] An error occurred (ThrottlingException) when calling   handlers.py:34
           the CreateCommit operation (reached max retries: 4):                 
           Rate exceeded                                                        
[11:20:32] No new councillor data found.                             base.py:317
           Finished attempting to scrape: ZET                        base.py:319
</pre>

  <h2 id="2022-03-09-11-57">2022-03-09</h2>
  <div class="ds-card">
  <div class="ds-card-body">
    <dl class="ds-descriptions">
      <div>
        <dt>Duration</dt>
        <dd>22 seconds</dd>
      </div>
      <div>
        <dt>Start</dt>
        <dd>2022-03-09 11:57:03.095519</dd>
      </div>
      <div>
        <dt>End</dt>
        <dd>2022-03-09 11:57:25.474891</dd>
      </div>
      <div>
        <dt>Status code</dt>
        <dd>200</dd>
      </div>
      <div>
        <dt>Error</dt>
        <dd>An error occurred (ConcurrentReferenceUpdateException) when calling the MergeBranchesBySquash operation: The merge cannot be completed because the following branch has been modified: refs/heads/main. Another user might have modified this branch while the merge was in progress. Wait a few minutes, and then try again.</dd>
      </div>
    </dl>
  </div>
  </div>

  <h3>Run log</h3>
  <pre>[11:57:13] Created log commit                                        base.py:376
           897412257d00f9e18dc5d7c75d723229b40d0d85                             
           Attempting to create merge commit...                      base.py:281
[11:57:25] An error occurred (ConcurrentReferenceUpdateException) handlers.py:34
           when calling the MergeBranchesBySquash operation: The                
           merge cannot be completed because the following branch               
           has been modified: refs/heads/main. Another user might               
           have modified this branch while the merge was in                     
           progress. Wait a few minutes, and then try again.                    
           Finished attempting to scrape: ZET                        base.py:319
</pre>

  <h2 id="2022-03-08-11-42">2022-03-08</h2>
  <div class="ds-card">
  <div class="ds-card-body">
    <dl class="ds-descriptions">
      <div>
        <dt>Duration</dt>
        <dd>12 seconds</dd>
      </div>
      <div>
        <dt>Start</dt>
        <dd>2022-03-08 11:42:53.640813</dd>
      </div>
      <div>
        <dt>End</dt>
        <dd>2022-03-08 11:43:06.203859</dd>
      </div>
      <div>
        <dt>Status code</dt>
        <dd>200</dd>
      </div>
      <div>
        <dt>Error</dt>
        <dd>An error occurred (InvalidTargetBranchException) when calling the MergeBranchesBySquash operation: Target branch parameter must point to either source or destination tip commit. Verify your target branch value is valid and then try again</dd>
      </div>
    </dl>
  </div>
  </div>

  <h3>Run log</h3>
  <pre>[11:43:00] Created log commit                                        base.py:376
           eec125e0310ae74c6e43a4467f54c2a1a230fa4a                             
           Attempting to create merge commit...                      base.py:281
[11:43:05] An error occurred (InvalidTargetBranchException) when  handlers.py:34
           calling the MergeBranchesBySquash operation: Target                  
           branch parameter must point to either source or                      
           destination tip commit. Verify your target branch                    
           value is valid and then try again                                    
[11:43:06] Finished attempting to scrape: ZET                        base.py:319
</pre>

  <h2 id="2022-03-07-12-03">2022-03-07</h2>
  <div class="ds-card">
  <div class="ds-card-body">
    <dl class="ds-descriptions">
      <div>
        <dt>Duration</dt>
        <dd>26 seconds</dd>
      </div>
      <div>
        <dt>Start</dt>
        <dd>2022-03-07 12:03:01.576140</dd>
      </div>
      <div>
        <dt>End</dt>
        <dd>2022-03-07 12:03:28.567021</dd>
      </div>
      <div>
        <dt>Status code</dt>
        <dd>200</dd>
      </div>
      <div>
        <dt>Error</dt>
        <dd>An error occurred (ConcurrentReferenceUpdateException) when calling the MergeBranchesBySquash operation: The merge cannot be completed because the following branch has been modified: refs/heads/main. Another user might have modified this branch while the merge was in progress. Wait a few minutes, and then try again.</dd>
      </div>
    </dl>
  </div>
  </div>

  <h3>Run log</h3>
  <pre>[12:03:14] Created log commit                                        base.py:376
           a1be30b4b933e9fd75a0118d63a19eeab9e2ec5e                             
           Attempting to create merge commit...                      base.py:281
[12:03:28] An error occurred (ConcurrentReferenceUpdateException) handlers.py:34
           when calling the MergeBranchesBySquash operation: The                
           merge cannot be completed because the following branch               
           has been modified: refs/heads/main. Another user might               
           have modified this branch while the merge was in                     
           progress. Wait a few minutes, and then try again.                    
           Finished attempting to scrape: ZET                        base.py:319
</pre>

  <h2 id="2022-03-07-11-36">2022-03-07</h2>
  <div class="ds-card">
  <div class="ds-card-body">
    <dl class="ds-descriptions">
      <div>
        <dt>Duration</dt>
        <dd>10 seconds</dd>
      </div>
      <div>
        <dt>Start</dt>
        <dd>2022-03-07 11:36:00.639141</dd>
      </div>
      <div>
        <dt>End</dt>
        <dd>2022-03-07 11:36:11.604642</dd>
      </div>
      <div>
        <dt>Status code</dt>
        <dd>200</dd>
      </div>
      <div>
        <dt>Error</dt>
        <dd></dd>
      </div>
    </dl>
  </div>
  </div>

  <h3>Run log</h3>
  <pre>[11:36:00] Fetching Scraper for: ZET                              handlers.py:22
           Begin attempting to scrape: ZET                        handlers.py:25
           Deleting existing data...                                 base.py:234
[11:36:01] Getting all files in ZET...                               base.py:186
           ...found 1 files in ZET                                   base.py:202
           Deleting batch no. 1 consisting of 1 files                base.py:211
[11:36:09] ...data deleted.                                          base.py:241
           Scraping from                                              base.py:40
           http://www.shetland.gov.uk/about_your_councillors/                   
[11:36:11] Finished attempting to scrape: ZET                        base.py:319
</pre>

  <h2 id="2022-03-07-00-17">2022-03-07</h2>
  <div class="ds-card">
  <div class="ds-card-body">
    <dl class="ds-descriptions">
      <div>
        <dt>Duration</dt>
        <dd>12 seconds</dd>
      </div>
      <div>
        <dt>Start</dt>
        <dd>2022-03-07 00:17:09.134280</dd>
      </div>
      <div>
        <dt>End</dt>
        <dd>2022-03-07 00:17:21.806457</dd>
      </div>
      <div>
        <dt>Status code</dt>
        <dd>200</dd>
      </div>
      <div>
        <dt>Error</dt>
        <dd>An error occurred (ConcurrentReferenceUpdateException) when calling the MergeBranchesBySquash operation: The merge cannot be completed because the following branch has been modified: refs/heads/main. Another user might have modified this branch while the merge was in progress. Wait a few minutes, and then try again.</dd>
      </div>
    </dl>
  </div>
  </div>

  <h3>Run log</h3>
  <pre>[00:17:14] Created log commit                                        base.py:376
           fc832c326e929a25b9f89fe5e54612350e46c6c9                             
           Attempting to create merge commit...                      base.py:281
[00:17:21] An error occurred (ConcurrentReferenceUpdateException) handlers.py:34
           when calling the MergeBranchesBySquash operation: The                
           merge cannot be completed because the following branch               
           has been modified: refs/heads/main. Another user might               
           have modified this branch while the merge was in                     
           progress. Wait a few minutes, and then try again.                    
           Finished attempting to scrape: ZET                        base.py:319
</pre>

  <h2 id="2022-03-07-00-05">2022-03-07</h2>
  <div class="ds-card">
  <div class="ds-card-body">
    <dl class="ds-descriptions">
      <div>
        <dt>Duration</dt>
        <dd>12 seconds</dd>
      </div>
      <div>
        <dt>Start</dt>
        <dd>2022-03-07 00:05:45.709399</dd>
      </div>
      <div>
        <dt>End</dt>
        <dd>2022-03-07 00:05:57.957964</dd>
      </div>
      <div>
        <dt>Status code</dt>
        <dd>200</dd>
      </div>
      <div>
        <dt>Error</dt>
        <dd>An error occurred (ThrottlingException) when calling the CreateCommit operation (reached max retries: 4): Rate exceeded</dd>
      </div>
    </dl>
  </div>
  </div>

  <h3>Run log</h3>
  <pre>[00:05:57] An error occurred (ThrottlingException) when calling   handlers.py:34
           the CreateCommit operation (reached max retries: 4):                 
           Rate exceeded                                                        
           Finished attempting to scrape: ZET                        base.py:319
</pre>

  <h2 id="2022-03-06-18-01">2022-03-06</h2>
  <div class="ds-card">
  <div class="ds-card-body">
    <dl class="ds-descriptions">
      <div>
        <dt>Duration</dt>
        <dd>3 seconds</dd>
      </div>
      <div>
        <dt>Start</dt>
        <dd>2022-03-06 18:01:27.731689</dd>
      </div>
      <div>
        <dt>End</dt>
        <dd>2022-03-06 18:01:31.011450</dd>
      </div>
      <div>
        <dt>Status code</dt>
        <dd>200</dd>
      </div>
      <div>
        <dt>Error</dt>
        <dd></dd>
      </div>
    </dl>
  </div>
  </div>

  <h3>Run log</h3>
  <pre>[18:01:27] Fetching Scraper for: ZET                              handlers.py:22
           Begin attempting to scrape: ZET                        handlers.py:25
           Deleting existing data...                                 base.py:234
[18:01:28] Getting all files in ZET...                               base.py:186
           ...found 1 files in ZET                                   base.py:202
           Deleting batch no. 1 consisting of 1 files                base.py:211
[18:01:29] ...data deleted.                                          base.py:241
           Scraping from                                              base.py:40
           http://www.shetland.gov.uk/about_your_councillors/                   
[18:01:30] Finished attempting to scrape: ZET                        base.py:319
</pre>

  <h2 id="2022-03-05-20-35">2022-03-05</h2>
  <div class="ds-card">
  <div class="ds-card-body">
    <dl class="ds-descriptions">
      <div>
        <dt>Duration</dt>
        <dd>13 seconds</dd>
      </div>
      <div>
        <dt>Start</dt>
        <dd>2022-03-05 20:35:20.429951</dd>
      </div>
      <div>
        <dt>End</dt>
        <dd>2022-03-05 20:35:34.053251</dd>
      </div>
      <div>
        <dt>Status code</dt>
        <dd>200</dd>
      </div>
      <div>
        <dt>Error</dt>
        <dd>An error occurred (ThrottlingException) when calling the CreateCommit operation (reached max retries: 4): Rate exceeded</dd>
      </div>
    </dl>
  </div>
  </div>

  <h3>Run log</h3>
  <pre>[20:35:33] An error occurred (ThrottlingException) when calling   handlers.py:33
           the CreateCommit operation (reached max retries: 4):                 
           Rate exceeded                                                        
[20:35:34] Finished attempting to scrape: ZET                        base.py:319
</pre>


      </main>
      <footer class="ds-footer">...</footer>
    </div>
  </body>
